---
layout: post
title: "Practica 01"
main-class: 'practica'
permalink: /SeminarioRyPython/SRyP:title.html
tags:
- nofunciona:c
- dos
- :oooo
introduction: "Texto de prueba."
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../SeminarioRyPython/_posts/", output_format = "all"  ) })
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../SeminarioRyPython/images/", "Clase02"),
               cache.path = "../../SeminarioRyPython/cache/")
```

## Introdução


```{r}
IC.wc <- function(x, n, conf.level=0.95){
  p <- x/n ; q <- 1-p
  alpha <- 1- conf.level
  z <- qnorm(p=alpha/2, lower.tail=FALSE)
  const1 <- z * sqrt(z^2 - 2 - 1/n + 4*p*(n*q+1)) 
  const2 <- z * sqrt(z^2 + 2 - 1/n + 4*p*(n*q-1)) 
  L <- (2*n*p + z^2 - 1 - const1) / (2*(n+z^2))
  U <- (2*n*p + z^2 + 1 + const2) / (2*(n+z^2))
  c(L, U)
}
rbind(2,3)
cbind(1,2)
IC.wc(x=35, n=50)
prop.test(x=35, n=50, correct=TRUE)$conf.int
```

BLA BLA BLA BLA

```{python}
## Python code
sum([1, 2, 3, 4, 5])
```


