---
layout: post
title: "Parcial II"
main-class: 'presentaciones'
permalink: /EstadisticaII/EstII:title.html
tags:

introduction: Parcial II

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaII/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaII/images/", "ParcialII"),
               cache.path = "../../EstadisticaII/cache/",
               cache = FALSE)
```

# Parcial
El planteamiento, resultados einterpretaciones deben realizarse a mano, y entregar el parcial al final de la clase >:(. 

* [Acevedo Zapata Alan Orlando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152220366.pdf){:target="_blank"}
* [Arango Bustos Danny](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1214748239.pdf){:target="_blank"}
* [Benavides Gavides Emily Alexandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1023623327.pdf){:target="_blank"}
* [Betancur Trespalacios Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001362881.pdf){:target="_blank"}
* [Cadavid Yarce Juan Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1044102034.pdf){:target="_blank"}
* [Cadena Yanascual Estefany Mishel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1085941354.pdf){:target="_blank"}
* [Cardona Ruiz Carlos Alberto](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1053767519.pdf){:target="_blank"}
* [Castro Perez Carlos Mario](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1002148318.pdf){:target="_blank"}
* [Echeverri Ramirez Wilfer Esneyder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000203437.pdf){:target="_blank"}
* [Flórez Jiménez Tomas](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152460117.pdf){:target="_blank"}
* [Garcia Escobar Cristian Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1038823759.pdf){:target="_blank"}
* [Garizabal Tibacuy Yorelis Patricia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1035435796.pdf){:target="_blank"}
* [Giraldo Alzate Yesica Paola](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007290732.pdf){:target="_blank"}
* [Gomez Hernandez Juan Esteban](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152471457.pdf){:target="_blank"}
* [Gómez Tobon Juan Pablo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152710331.pdf){:target="_blank"}
* [Londoño Sepulveda Marisol](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001580456.pdf){:target="_blank"}
* [Mora Bedoya Rubén Darío](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1039460833.pdf){:target="_blank"}
* [Morales Valencia Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007346784.pdf){:target="_blank"}
* [Mosquera Merchan Maria Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000870935.pdf){:target="_blank"}
* [Murillo Madrigal Odalis Paola](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017265065.pdf){:target="_blank"}
* [Ocampo Salazar Durley Alberto](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1047964029.pdf){:target="_blank"}
* [Penaranda Saldarriaga Brayan](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001391063.pdf){:target="_blank"}
* [Roldán Muñoz Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128387647.pdf){:target="_blank"}
* [Sosa Giraldo Estiven](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000764590.pdf){:target="_blank"}
* [Vergara Ochoa Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037642829.pdf){:target="_blank"}

<h1> Mucha Suerte! :D </h1>

