---
layout: post
title: "Parcial I"
main-class: 'presentaciones'
permalink: /EstadisticaII/EstII:title.html
tags:

introduction: Parcial I

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaII/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaII/images/", "ParcialI"),
               cache.path = "../../EstadisticaII/cache/",
               cache = FALSE)
```

# Parcial
La solución, paso a paso e interpretaciones deben realizarse a mano, y entregar el parcial al final de la clase >:(. 

# Nota
Pueden apoyarse para el cálculo de probabilidades o integrales en \texttt{R} u otra herramienta, pero los procedimientos tales como **TRANSFORMACIONES** y **PLANTEAMIENTO DE PROBABILIDADES**, **INTERPRETACIONES** deben realizarse **PASO A PASO** y a mano >:(

* [Bedoya Vargas Julian Alirio](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1039474881.pdf){:target="_blank"}
* [Blanco Yarce Juan David](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1044500706.pdf){:target="_blank"}
* [Cardona Tabares Yeison](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1040051828.pdf){:target="_blank"}
* [Duque Orrego Valentina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1044100047.pdf){:target="_blank"}
* [Garcia Escobar Cristian Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1038823759.pdf){:target="_blank"}
* [Gonzalez Munevar Laura Sofia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1052838196.pdf){:target="_blank"}
* [Grajales Lezcano Jeferson](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001144033.pdf){:target="_blank"}
* [Jimenez Ramirez Luis Fernando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1003066798.pdf){:target="_blank"}
* [Londoño Guzman Yuber Alonso](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128399856.pdf){:target="_blank"}
* [Marin Jaramillo John Arturo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017129376.pdf){:target="_blank"}
* [Montoya Pabon Valentina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1020222282.pdf){:target="_blank"}
* [Ospina Agudelo Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007346941.pdf){:target="_blank"}
* [Portilla Benavides Karen Vanessa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1086774044.pdf){:target="_blank"}
* [Quirama Pino David Camilo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1214744036.pdf){:target="_blank"}
* [Ramirez Herrera Jhonatan Alexander](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1040042534.pdf){:target="_blank"}
* [Rivillas Ochoa Paula Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001416490.pdf){:target="_blank"}
* [Rodriguez Herrera Isabella](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1025642615.pdf){:target="_blank"}
* [Sandoval Ramirez Joel Alejandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1014661670.pdf){:target="_blank"}
* [Vargas Acevedo Maria Leonor](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007142409.pdf){:target="_blank"}
* [Vargas Moreno Oreilys Ayari](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P3296612.pdf){:target="_blank"}
* [Vasco Agudelo Juan Pablo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037662204.pdf){:target="_blank"}
* [Vásquez López Juan Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128444892.pdf){:target="_blank"}


<h1> Mucha Suerte! :D </h1>

