---
layout: post
title: "Parcial III"
main-class: 'presentaciones'
permalink: /EstadisticaII/EstII:title.html
tags:

introduction: Parcial III

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaII/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaII/images/", "ParcialII"),
               cache.path = "../../EstadisticaII/cache/",
               cache = FALSE)
```

# Trabajo
El trabajo aquí planteado tienen por objetivo **evaluar la temática que corresponde a la tercera evaluación del curso** de Estadística II, en donde dicha temática corresponde a las unidades `$4$` y `$5$` del microcurrículo del curso, a saber, estimación por intervalos y prueba de hipótesis.

Este trabajo tiene un peso del `$30\%$` en la nota definitiva del curso y por ello **se aconseja leer cuidadosamente** cada una de las anotaciones aquí planteadas para no cometer errores en el planteamiento de los puntos, el envío de los documentos finales o la fecha límite de entrega.

El trabajo debe realizarse de forma individual, y se **tiene como plazo máximo entrega** el día **24 de Agosto** a las **12PM** al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>, mencionando en el asunto **Trabajo Estadística II** junto con el grupo al cual pertenece **M-J** o **W-V**. Correos enviados luego de la fecha y hora establecidas no serán revisados, así que traten de enviarlos con antelación.

Para el desarrollo del trabajo **usted deberá buscar una o varias bases de datos** que le permitan estructurar y resolver una serie de preguntas relacionadas con el tema de intervalos de confianza y pruebas de hipótesis, en donde **el objetivo será reestructurar o adaptar las preguntas generales** que se realizarán en este trabajo, para que éstas queden estructuradas en el contexto y la temática que seleccionó para su base de datos y poder realizar las conclusiones correspondientes a cada punto en el contexto de los datos.

# Entregables 
Entre los documentos que se deben enviar al correo una vez finalice el trabajo se destaca

* **Documento Word, o pdf**, en el cual se realiza el desarrollo del trabajo, es decir, documento en donde se plantean los puntos reestructurados, la explicación de las bases de datos, los cálculos de las variables, el desarrollo de los ejercicios y las conclusiones correspondientes.
* **Hoja u Hojas de Excel o texto**, con la base o bases de datos utilizadas. Si se encuentran en el mismo documento de Excel todas las bases de datos traten de enumerarlas para identificar cuál usaron en cada punto.
* **Script de R, documento de texto, archivo de Excel** o formato de archivo en el cual realicen todos los cálculos que no hayan hecho manuales, tales como pruebas de normalidad, calculo de probabilidades, calculo de cuartiles, etc.
* **Otros documentos** que consideren de interés, ya sea para explicar el contexto a la base de datos o explicar algún procedimiento que se aplicó en el desarrollo del trabajo y que considere importante.

# Preguntas
1) **(0.5 puntos)** Realice una contextualización sobre la o las bases de datos que seleccionó para resolver cada uno de los punto presentados a continuación, explicando cuál es el contexto de las bases de datos, por qué hizo la selección de la misma y cómo podría darle un uso desde su perfil de Economista o Administrador de Empresas.
2) **(0.5 puntos)** Presente un diagnóstico inicial de las bases de datos, en donde el objetivo es presentar de forma gráfica o numérica el comportamiento de la base de datos a través de un análisis descriptivo de las diferentes variables.
3) **(0.5 puntos)** Seleccione una variable numérica, y plantee con ésta un intervalo de confianza o una prueba de hipótesis para el verdadero promedio de dicha variable.
4) **(0.5 puntos)** Seleccione una variable numérica, y divídala en dos categorías asociados a una variable cualitativa, con el fin de plantear un intervalo de confianza o una prueba de hipótesis para la comparación entre el verdadero promedio de dos poblaciones.
5) **(0.5 puntos)** Seleccione una variable cualitativa, y desarrolle un intervalo de confianza o una prueba de hipótesis para la verdadera proporción de esa variable.
6) **(0.5 puntos)** Seleccione una variable cualitativa que pueda dividir en dos grupos, y con éstos plantee un intervalo de confianza o una prueba de hipótesis para la diferencia entre la verdadera proporción de las dos poblaciones.
7) **(0.5 puntos)** Seleccione una variable numérica, y con ésta construya un intervalo de confianza o una prueba de hipótesis para la verdadera varianza.
8) **(0.5 puntos)** Seleccione una variable numérica, y divídala en dos grupos asociados a una variable cualitativa, con el fin de construir un intervalo de confianza o una prueba de hipótesis para la verdadera razón de varianzas.
9) **(0.5 puntos)** Selecciones dos variables cualitativas, para probar si existe o no una relación de dependencia entre las categorías que conforman las variables.
10) **(0.5 puntos)** Selecciones una variable numérica, y trate de identificar cuál es la distribución de probabilidad que presenta un mejor ajuste para dicha variable.

# Nota
* Ninguno de los puntos le especifica a usted cuál es el nivel de confianza o nivel de significancia que debe usar, así que la selección de dichos niveles debe ser escogido a su criterio.
* La mayoría de los puntos le dan la posibilidad de elegir entre plantear un intervalo de confianza o una prueba de hipótesis, así que trate de alternar las pruebas que usa, o trate de seleccionar cuál de las dos es más adecuada en base al contexto de su base de datos y a lo que quiere mostrar.
* Los enunciados de **todas las preguntas** deben ser reestructurados de tal forma que éstos queden planteados según el contexto de su base de datos, tal como se les explicó en clase con lo de **pregunta genérica => pregunta reestructurada**.
* Asegúrese de registrar en el documento de Word todos los procedimientos que haya realizado para la solución de los puntos, ya que un trabajo con vacíos metodológicos es un trabajo mal realizado.

# Preguntas Frecuentes (FAQ)
* ¿Profe por qué puso ese trabajo tan largo?

<button id="Show1" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide1" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito1"> 
<p>R:/ La razón se debe a que debo evaluar si son capaces de plantear y desarrollar sus propias preguntas sobre un objeto de estudio, ya que es probable que deban enfrentar una situación similar cuando se encuentren realizando sus prácticas profesionales o propiamente en el trabajo, y qué mejor lugar que realizar esto cuando aún están en un "aula de clase". </p>
</main>
* ¿Profe no podía haber puesto el trabajo más cortico?

<button id="Show2" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide2" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito2"> 
<p>R:/ De poder poder..., obvio si hubiera podido poner el trabajo más corto, pero como tienen toda una semana para realizar el trabajo y no hay forma de evitar de que se ayuden unos a otros, la idea es que al menos tengan que estudiar los diferentes escenarios sobre intervalos de confianza y pruebas de hipótesis, antes de desarrollar los puntos. </p>
</main>
* ¿Profe en el punto 1) a qué se refiere con el término "darle un uso desde su perfil de Economista o Administrador de Empresas"?

<button id="Show3" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide3" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito3"> 
<p>R:/ Cómo la idea del trabajo es que no seleccionen las bases de datos al azar, si no que traten de seleccionarlas en base a algún área de interés que puedan tener, entonces el objetivo es que busquen un contexto en el cual puedan emplear dicha base de datos desde las áreas de aplicación de su formación profesional. <br>
<br>
<strong>Ejemplo</strong>: Mi base de datos trata sobre el número de nuevas viviendas que se han construido en los diferentes municipios de Antioquia durante los últimos meses. 

Entonces la razón para seleccionar dicha base de datos se debe a que ésta puede darme una visión sobre cuáles son los municipios en los cuales se está realizando mayor inversión en construcción de viviendas, me permite observar si hay o no diferencias significativas entre el número de viviendas que se construyen para diferentes municipios, y me sirve de insumo para observar si es posible implementar algún tipo de política pública que busque incentivar la construcción de nuevas viviendas en aquellos municipios que presentan menor crecimiento. </p>
</main>
* ¿Profe a qué se refiere en el punto 2) con "realizar un diagnóstico inicial de la base de datos", el tema de Estadística Descriptiva no es un tema de Estadística I?

<button id="Show4" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide4" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito4"> 
<p>R:/ Si, la temática de Estadística Descriptiva para una base de datos es un concepto que se abordó en el curso de Estadística I, pero la fase de descripción de la base de datos siempre es el primer paso de cualquier trabajo aplicado, independientemente del análisis que se vaya a realizar con la base de datos. 
<br>
<br>
Así que pueden apoyarse en las notas de clase presentadas en la <a href="https://jiperezga.github.io/EstadisticaI/EstIClase04.html#media" target="\_blank">Clase 04</a> y la <a href="https://jiperezga.github.io/EstadisticaI/EstIClase05.html#media" target="\_blank">Clase 05</a> del curso de Estadística I, pues en estas encontrarán formas para realizar análisis descriptivos para variables cualitativas y cuantitativas, y cuales son los gráficos más adecuados para presentar la información dependiendo del tipo de variable que se tenga.
</p>
</main>
* ¿Profe entonces yo escojo los niveles de confianza o significancia que quiera?

<button id="Show5" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide5" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito5"> 
<p>R:/ Si, la selección del nivel de confianza $1-\alpha$ o nivel de significancia $\alpha$ queda a su criterio, solo trate de recordar que niveles comúnmente empleados en la práctica son $\alpha = 0.1, 0.05, 0.01$, así que trate de seleccionar siempre valores cercanos a la cola de la distribución, evitando usar valores del tipo $\alpha = 0.43$, $\alpha = 0.71$, etc.
</p>
</main>
* ¿Profe cuando me menciona en el punto 4) el punto 6), que seleccione una variable y la divida en dos grupos a qué se refiere?

<button id="Show6" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide6" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito6"> 
<p>R:/ Recuerden que para emplear intervalos de confianza o pruebas de hipótesis para diferencia de medias, diferencia de proporciones o razón de varianzas, la ideas es tomar la misma variable numérica dividida en dos grupos, <strong>por ejemplo</strong>, salario de hombres VS salario de mujeres, para observar si hay diferencias significativas entre los grupos. Así que recuerden la forma en cómo hacer filtros para poder dividir una variable en dos grupos.
</p>
</main>
* ¿Profe las variables que uso en el punto 3 y punto 4, pueden ser las mismas que uso en el punto 7 y 8?

<button id="Show7" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide7" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito7"> 
<p>R:/ Sí, realmente no hay ninguna regla que impida que uses la misma variable para plantear dos tipos de intervalos o pruebas de hipótesis diferentes.
</p>
</main>
* ¿Profe en el punto 5 y 6, que son pruebas para proporciones, debo seleccionar necesariamente variables cualitativas?

<button id="Show8" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide8" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito8"> 
<p>R:/ No tienes que seleccionar necesariamente variables cualitativas, recuerda que tu puedes seleccionar una variable numérica y transformarla a cualitativa al establecer diferentes niveles para la variable. Lo que si es necesario es que los niveles de esa variable estén sustentados de alguna forma.<br>
<br>
<strong>Ejemplo</strong>: Mi base de datos trata sobre el tiempo que tienen que esperar un grupo de pacientes hasta ser atendidos en una unidad de urgencias. 

Entonces en este caso podría discretizar la variable de tiempos de espera, basándome en los diferentes niveles de TRIAGE que se establecen en una unidad de urgencias, en donde por ejemplo, el TRIAGE II representa código Naranja, es decir, tiempos de espera que van de 10 a 15 minutos.</p>
</main>
* ¿Profe, que hago si en el punto 7 u 8 se rechaza la hipótesis de normalidad?

<button id="Show9" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide9" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito9"> 
<p>R:/ Recuerden que para realizar un intervalo de confianza o una prueba de hipótesis para una varianza o cociente de varianzas, es necesario que los datos que usted va a utilizar se distribuyan normalmente, pero en caso de que no se cumpla tal supuesto de normalidad, podría realizar un supuesto de normalidad en caso de tener tamaños de muestra suficientemente grandes o podría buscar otra variable que no rechace el supuesto de normalidad, en caso de tener muestras pequeñas.

<strong>Nota:</strong> Si en el peor de los casos no logra encontrar una base de datos más grande, o que no rechace el supuesto de normalidad, puede recurrir a un proceso de simulación, en donde emplee una distribución normal con media poblacional $\mu=\bar{X}$ y desviación estándar poblacional $\sigma=S$, con el fin de realizar los análisis relacionados. Recuerde en este escenario, <strong>establecer una semilla antes de realizar las simulaciones.</strong>
</p>
</main>
* ¿Profe, de verdad le parece justo ponernos un trabajo de 10 puntos?

<button id="Show10" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide10" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito10"> 
<p>R:/ Es el 30% de la materia lo que tienen en juego, así que creo que un trabajo de 10 punto para desarrollar en una semana si es algo justo.
<br>
<br>Además si fuera menos exigente con ustedes, seguramente ya me hubieran echado de la Universidad por vago y estaría viviendo debajo de un puente o algo así.</p>
</main>
* ¿Profe en el punto 9, deben cumplir algún tipo de característica las variables cualitativas seleccionadas?

<button id="Show11" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide11" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito11"> 
<p>R:/ La única condición que deben cumplir es que las dos variables cualitativas pertenezcan a la misma base de datos, y por tanto tengan la misma longitud. Es decir, no puedo usar una variable que encontré una base de datos y otra variable que encontré en otra base de datos, porque no habría forma alguna de construir con estas una tabla de contingencia.</p>
</main>
* ¿Profe en el punto 10, cómo se cuál es la distribución que presenta un mejor ajuste?

<button id="Show12" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide12" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito12"> 
<p>R:/ Recuerden que hay diferentes formas para probar si los datos se ajustan realmente a un conjunto de datos, a través de pruebas estadísticas y a través de gráficos, así que trate de apoyarse en aquellos ajustes que le presenten mejores P-valores en diferentes pruebas estadísticas, y en aquel que presente una mayor cantidad de puntos dentro de las bandas de confianza del QQ-plot, buscando siempre los puntos que se acerquen más a la recta diagonal.</p>
</main>
* ¿Profe no me queda claro qué hay que enviarle?

<button id="Show13" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide13" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito13"> 
<p>R:/ Como mínimo hay que enviar 3 archivos:<br>
1) El documento de Word o del editor de texto que hayan utilizado con todas las interpretaciones, gráficos, y demás salidas de programación que hayan realizado para solucionar los ejercicios.<br>
2) Las bases de datos que utilizaron, ya sea que las usó en formato de Excel, en formato csv, en formato txt, etc.<br>
3) El código de R utilizado, ya que en el peor de los casos tuvieron que utilizar el programa para realizar las pruebas de bondad de ajuste para probar normalidad. <br>
<br>
Si realizaron las operaciones matemáticas y demás cálculos en otro programa diferente a R, entonces me envían también esos desarrollos, ya que debo verificar la forma en cómo hicieron los cálculos y si dichos cálculos se realizaron correctamente.
</p>
</main>
* ¿Profe si envío el trabajo luego de las 12 de la noche del martes que pasa?

<button id="Show14" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide14" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito14"> 
<p>R:/ Simplemente no se revisa el trabajo y quedarías con un 0 en la nota asociada al 30% de la materia que se evaluó.
</p>
</main>
* ¿Profe se puede pedir supletorio de esta actividad evaluativa?

<button id="Show15" class="btn btn-secondary">Mostrar Respuesta</button>
<button id="Hide15" class="btn btn-info">Ocultar Respuesta</button>
<main id="botoncito15"> 
<p>R:/ Dado que se tiene un plazo de siete días para realizar la actividad, tendrían que presentar una excusa médica o una carta del Papa, en donde conste que estuvieron en coma clínico durante dicha semana, y que debido a eso no pudieron realizar la actividad evaluativa.
</p>
</main>


<h1> Mucha Suerte! :D </h1>

