---
layout: post
title: "Parcial III"
main-class: 'presentaciones'
permalink: /EstadisticaII/EstII:title.html
tags:

introduction: Parcial III

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaII/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaII/images/", "ParcialIII"),
               cache.path = "../../EstadisticaII/cache/",
               cache = FALSE)
```
# Parcial III
El parcial pueden solucionarlo a mano o en Word, y enviar al final de la clase al correo jivan.perez@udea.edu.co, el desarrollo de los puntos y los códigos generados para tal objetivo. D:<

Quedo atento a cualquier duda o inquietud que les surja durante el trabajo. No duden en preguntar, pero no pretendan que les haga el punto >:|

# Nota
**Lea atentamente el parcial**. Recuerden interpretar todos los resultados en el contexto del enunciado!!!, **no hacerlo les va hacer perder punto!!!!** >:c

# Bases y enunciados
## Barbosa Esteban Brayan Felipe
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1005028536.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1005028536.csv){:target="_blank"}

## Bastidas Burbano Jose Manuel
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1138524086.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1138524086.csv){:target="_blank"}

## Britto Zapata Nicolas
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1035305565.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1035305565.csv){:target="_blank"}

## Builes Tobon Lorena
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1001228196.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1001228196.csv){:target="_blank"}

## Cadavid Yarce Juan Felipe
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1044102034.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1044102034.csv){:target="_blank"}

## Cardona Acosta Jacobo
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1089931364.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1089931364.csv){:target="_blank"}

## Correa Romero David
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1000557127.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1000557127.csv){:target="_blank"}

## Flórez Jiménez Tomas
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1152460117.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1152460117.csv){:target="_blank"}

## Guarin Moreno Laura Marely
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1020104926.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1020104926.csv){:target="_blank"}

## Hernandez Salazar Juana Valentina
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1193579747.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1193579747.csv){:target="_blank"}

## Jaramillo Galvis Jhon
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1004347892.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1004347892.csv){:target="_blank"}

## Lopez Reyes Leyfor David
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1083876251.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1083876251.csv){:target="_blank"}

## Martin Vivas Fernando Elias
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1017250715.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1017250715.csv){:target="_blank"}

## Mesa Jimenez Alejandro
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1192832074.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1192832074.csv){:target="_blank"}

## Murillo Rojas Karen Sofia
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1000445568.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1000445568.csv){:target="_blank"}

## Ocampo Rico David Santiago
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1001478035.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1001478035.csv){:target="_blank"}

## Perez Lopez Emmanuel
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1020332073.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1020332073.csv){:target="_blank"}

## Pertuz Sanchez Andres Camilo
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1137975166.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1137975166.csv){:target="_blank"}

## Quirama Pino David Camilo
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1214744036.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1214744036.csv){:target="_blank"}

## Restrepo Maya Salome
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1013457769.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1013457769.csv){:target="_blank"}

## Serna Palacio Kevin Alexander
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1048020998.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1048020998.csv){:target="_blank"}

## Vergara Ochoa Daniel
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1037642829.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1037642829.csv){:target="_blank"}

## Viana Alvarez Evelin Steffy
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/T1002146503.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/B1002146503.csv){:target="_blank"}

<h1> Mucha Suerte! </h1>

