---
layout: post
title: "Parcial V"
main-class: 'practica'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Parcial V 6-8 PM

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "ParcialV"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)
```

# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 8:30 pm, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>.

# Nota 1
Una vez planteado el ejercicio con la distribución de probabilidad identificada, pueden emplear cualquier herramienta para calcular el valor de la probabilidad, y recuerden **interpretar los resultados en el contexto del ejercicio**.

# Nota 2
Pilas con las probabilidades condicionales, la relación entre la distribución Exponencial y la Poisson, y con el hecho de que la distribución Gamma es la ocurrencia de múltiples distribuciones Exponenciales.

# Nota 3
Dudas que se les generen sobre cualquier punto me pueden escribir al correo, es mejor intentar resolverlas, que dejarlas al aire y tirarse los puntos.

* [Benjumea Valderrama Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1214729562.pdf){:target="_blank"}
* [Carrascal Vergara Mario Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1035442052.pdf){:target="_blank"}
* [Gamboa Zarate Mayra Valentina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1192792284.pdf){:target="_blank"}
* [Gil Zapata Izara Paulina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152201907.pdf){:target="_blank"}
* [González Ramírez Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128395206.pdf){:target="_blank"}
* [Jiménez De Avila Rodrigo Esteban](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037484188.pdf){:target="_blank"}
* [Lascarro Medina Andres Ricardo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1053006264.pdf){:target="_blank"}
* [Mancipe Soler Javier Alberto](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1049024349.pdf){:target="_blank"}
* [Martínez Moreno Diego Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128399344.pdf){:target="_blank"}
* [Mejia Erazo Kevin](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1003125429.pdf){:target="_blank"}
* [Mira Gil Laura Cristina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017139650.pdf){:target="_blank"}
* [Otalvaro Londono Alejandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1214728316.pdf){:target="_blank"}
* [Pareja Pérez Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017238280.pdf){:target="_blank"}
* [Ramírez Cossio Yeison Esneider](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1146443209.pdf){:target="_blank"}
* [Roldán Muñoz Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1128387647.pdf){:target="_blank"}
* [Valencia Zapata Andres Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1035443367.pdf){:target="_blank"}
* [Zuluaga Murillo Vivian Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1010098601.pdf){:target="_blank"}

<h1> Mucha Suerte! </h1>
