---
layout: post
title: "Clase 04"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Introducción a la probabilidad, fundamentos y teoría de conjuntos.
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase03"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Fundamentos de probabilidad
### Noción de aleatoriedad
La aleatoriedad está asociada a todo proceso cuyo resultado no puede ser determinado antes de que éste se produzca, debido a que los resultados de dicho proceso no contiene patrones reconocibles o regulares, que permitan pronosticar un resultado futuro.

### Experimento aleatorio
Es aquel experimento que, a pesar de controlar las condiciones iniciales bajo las cuales se realiza, no es posible garantizar los mismos resultados que se obtienen inicialmente, debido a que su resultado es determinado por el azar.

### Experimento estadístico
Es cualquier acción o proceso que proporciona un conjunto de resultados, ya sean numérico o no numéricos. Éstos deben cumplir ciertas características:

* No es posible predecir el resultado exacto del experimento, en cualquiera de sus ejecuciones.
* Es posible conocer todos los posibles resultados del experimento, previo a las realizaciones del mismo.
* Es posible repetir el experimento bajo condiciones identicas o similares.

### Espacio muestral
Es el conjunto de todos los posibles resultados de un experimento estadístico. Generalmente, el espacio muestral se denota por la letra `$S$` o la letra griega `$\Omega$`.

### Evento de un espacio muestral
Es un subconjunto de los resultados del espacio muestral S. Generalmente, los eventos se denotan por las primeras letras del abecedario de la forma `$A, B, C$` o `$A_1, A_2, A_3$`.

Los eventos pueden ser clasificados en dos tipos

* **Simple:** se da cuando el evento tiene más de un resultado o punto muestral.
* **Compuesto:** se da cuando el evento tiene más de un resultado o punto muestral. Estos resultados pueden ser dependientes o independientes.

## Teoría de conjuntos
Dado que un evento puede estar compuestos por un conjunto de datos, las relaciones y resultados de la teoría de conjuntos puede ser utilizados
1. El **complemento** de un evento `$A$` respecto al espacio muestral `$S$`, es denotado por `$A^c$` o `$A'$`, y se define como el subconjunto de todos los elementos de `$S$` que no están contenidos en `$A$`.
2. La **unión** de dos eventos `$A$` y `$B$`, es denotado por `$A\cup B$`, y se define como el evento que contiene todos los elementos que pertenecen a `$A$` o `$B$` o ambos.
3. La **intersección** de dos eventos `$A$` y `$B$`, es denotado por `$A\cap B$`, es el evento que contiene todos los elementos que son comunes en `$A$` y `$B$`.
4. Los eventos `$A$` y `$B$` son **mutuamente excluyentes** cuando `$A\cap B=\oslash$`, donde `$\oslash$` se denota como el evento nulo.

## Probabilidad
La probabilidad es una medida asociada a la posibilidad de que ocurra un determinado evento, en donde, la forma forma tradicional de estimar la probabiladad es mediante el concepto de frecuencia relativa.
`\begin{align*}
\text{Frecuencia relativa} = \frac{\text{Número de puntos muestrales del evento de interés}}{\text{Total puntos en el espacio muestral}}
\end{align*}`

### Axiomas de probabilidad

## Referencias


