---
layout: post
title: "Clase 05"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Tecnicas de conteo
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase05"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Continuación técnicas de conteo
### Teorema: Combinatoria
El número de combinaciones de `$n$` objetos, tomando `$r$` objetos a la vez, es el número de subconjuntos de tamaño `$r$`, que se pueden formar a partir de los `$n$` objetos. Entonces, el número de subconjuntos desordenados de tamaño `$r$` escogidos sin reemplazo, de un total de `$n$` objetos disponibles es
`\begin{align*}
_nC_r=\left(\begin{array}{c}n\\ r\end{array}\right) = \frac{n!}{r! (n-r)!}
\end{align*}`

### Teorema: Combinatoria por subconjuntos
El número de maneras en que un conjunto de `$n$` objetos diferentes se puede dividir o partir en `$k$` subconjuntos de `$n_1$` objetos el primer subconjunto, `$n_2$` objetos el segundo subconjunto, `$\ldots$`, y `$n_k$` objetos el `$k$`-ésimo subconjunto es
`\begin{align*}
\left(\begin{array}{c}n\\ n_1, n_2, \ldots, n_k\end{array}\right) = \frac{n!}{n_1! n_2! \ldots n_k!}
\end{align*}`

siendo `$\sum_{i=1}^kn_i=n$`.

### Nota
Si se tienen `$n$` objetos de los cuales se desean tomar `$r$` a la vez, se debe hacer distinción, si el conteo se realiza con reemplazo o sin reemplazo, además, se debe determinar si los objetos deben estar ordenados o no

#### Caso 1: Con orden, sin reemplazo
`\begin{align*}
_nP_r= n(n-1)(n-2)\ldots(n-r+1)=\frac{n!}{(n-r)!}\\
\end{align*}`

#### Caso 2: Con orden, con reemplazo
`\begin{align*}
n^r
\end{align*}`

#### Caso 3: Sin orden, sin reemplazo
`\begin{align*}
_nC_r = \left(\begin{array}{c}n\\ r\end{array}\right) = \frac{n!}{r! (n-r)!}
\end{align*}`

#### Caso 4: sin orden con reemplazo
`\begin{align*}
_{n+r-1}C_r = \left(\begin{array}{c}n+r-1\\ r\end{array}\right) = \frac{n+r-1!}{r! (n-1)!}
\end{align*}`

