---
layout: post
title: "Trabajo"
main-class: 'presentaciones'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Trabajo R

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Trabajo"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)
```

# Trabajo T
El trabajo deberá solucionarse y enviar los resultado con los análisis correspondientes el día Martes a las 11:59 PM, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>.

Recuerden que si van a hacer el trabajo en parejas, deben unir las dos bases de datos.

Quedo atento a cualquier duda o inquietud que les surja durante el trabajo. No duden en escribirme.

## Enunciado trabajo 
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/TrabajoR.docx){:target="_blank"}

## Bases de datos 
* [Acevedo Zapata Alan Orlando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1152220366.xlsx){:target="_blank"}
* [Agudelo Pulgarín Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1020471882.xlsx){:target="_blank"}
* [Arango Ocampo Alexander](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1021803535.xlsx){:target="_blank"}
* [Benjumea Villa Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1193526570.xlsx){:target="_blank"}
* [Bohorquez Mendez Marinella](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1007528579.xlsx){:target="_blank"}
* [Cadavid Ortiz Susana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000885105.xlsx){:target="_blank"}
* [Cano Agudelo Yeison Leandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1035869894.xlsx){:target="_blank"}
* [Cardona Escudero Harold](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1036681549.xlsx){:target="_blank"}
* [Córdoba Cadena Santiago Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1004236627.xlsx){:target="_blank"}
* [Durango Gonzalez Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1020495523.xlsx){:target="_blank"}
* [Echeverri David Andres Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000296059.xlsx){:target="_blank"}
* [Franco Rodriguez Sebastian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037237922.xlsx){:target="_blank"}
* [Gallo Muñoz Ana Maria](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1036782913.xlsx){:target="_blank"}
* [Garavito Garcia Paola](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1152468344.xlsx){:target="_blank"}
* [Garcia Correa Maria Antonia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000417107.xlsx){:target="_blank"}
* [García Montoya Johan Andrés](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017248422.xlsx){:target="_blank"}
* [Garizabal Tibacuy Yorelis Patricia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1035435796.xlsx){:target="_blank"}
* [Giraldo Cardona Maria Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1007374227.xlsx){:target="_blank"}
* [Gómez Zuluaga Eva Maria](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1234989002.xlsx){:target="_blank"}
* [Hincapié Tabares Moisés](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017242109.xlsx){:target="_blank"}
* [Jaimes Diaz Maria Camila](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000533983.xlsx){:target="_blank"}
* [Jaramillo Galvis Jhon](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1004347892.xlsx){:target="_blank"}
* [Loaiza Castaño Silbana Alexandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T43876694.xlsx){:target="_blank"}
* [Lopera Jimenez Paula Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001368406.xlsx){:target="_blank"}
* [Luna Lozano Jaison Yesid](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1010134743.xlsx){:target="_blank"}
* [Madrigal Cordoba Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000189381.xlsx){:target="_blank"}
* [Marín Agudelo Jefferson Arley](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017227638.xlsx){:target="_blank"}
* [Martinez Sosa Andrea Catalina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017159829.xlsx){:target="_blank"}
* [Mendoza Reyes Estefania](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000393614.xlsx){:target="_blank"}
* [Mesa Jimenez Samantha](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037669405.xlsx){:target="_blank"}
* [Moya Beltran Angela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1006827132.xlsx){:target="_blank"}
* [Muñoz Cardona Maria Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000444797.xlsx){:target="_blank"}
* [Muñoz Torres Jurany](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017260249.xlsx){:target="_blank"}
* [Murillo Chavera Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1214713668.xlsx){:target="_blank"}
* [Navarro Gonzalez Veronica](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1003290622.xlsx){:target="_blank"}
* [Noreña Ocampo Jensy Lorena](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037666245.xlsx){:target="_blank"}
* [Ochoa Arboleda María Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000291035.xlsx){:target="_blank"}
* [Pacheco Herrera Laura](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1036678548.xlsx){:target="_blank"}
* [Patiño Valencia Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037649063.xlsx){:target="_blank"}
* [Penagos Areiza Karla](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001028460.xlsx){:target="_blank"}
* [Pérez Rios Mariana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1036686814.xlsx){:target="_blank"}
* [Perez Sierra Kelly Johana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1035880049.xlsx){:target="_blank"}
* [Piedrahita Palacio Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001456425.xlsx){:target="_blank"}
* [Quintero Borja Camilo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1214741162.xlsx){:target="_blank"}
* [Raigosa Toro Laura Mayeli](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1152463340.xlsx){:target="_blank"}
* [Ramirez Uribe Simon](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037667721.xlsx){:target="_blank"}
* [Rendón Giraldo Juan Camilo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001525914.xlsx){:target="_blank"}
* [Reyes Herrera Jerson David](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1030653675.xlsx){:target="_blank"}
* [Rivero Sanchez Daniela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1003077941.xlsx){:target="_blank"}
* [Rodriguez Ordoñez Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1002961486.xlsx){:target="_blank"}
* [Serna Garcia Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001755948.xlsx){:target="_blank"}
* [Torres  Lubin Fernando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T71388332.xlsx){:target="_blank"}
* [Vásquez López Juan Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1128444892.xlsx){:target="_blank"}
* [Velasquez Parra Maria Paulina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000295879.xlsx){:target="_blank"}
* [Victoria Florez Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1192779829.xlsx){:target="_blank"}
* [Villa Hincapiè Isabella](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000410842.xlsx){:target="_blank"}
* [Zapata Tinoco Angie Melisa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1152457136.xlsx){:target="_blank"}
* [Zuleta Cortes Alejandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001481021.xlsx){:target="_blank"}



<h1> Mucha Suerte! </h1>
