---
layout: post
title: "Supletorio III"
main-class: 'presentaciones'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Supletorio III

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "ParcialIII"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)
```
# Supletorio
El Supletorio deberá solucionarse y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 12:00 m, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
**Recuerden interpretar todos los resultados** en el contexto del enunciado!!!, no hacerlo les va hacer perder punto!!!! >:c

* [Acevedo Zapata Alan Orlando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1152220366.pdf){:target="_blank"}
* [Córdoba Cadena Santiago Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1004236627.pdf){:target="_blank"}
* [Franco Rodriguez Sebastian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1037237922.pdf){:target="_blank"}
* [Garavito Garcia Paola](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1152468344.pdf){:target="_blank"}
* [Jaramillo Galvis Jhon](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1004347892.pdf){:target="_blank"}
* [Luna Lozano Jaison Yesid](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1010134743.pdf){:target="_blank"}
* [Marín Agudelo Jefferson Arley](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1017227638.pdf){:target="_blank"}
* [Mendoza Reyes Estefania](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1000393614.pdf){:target="_blank"}
* [Muñoz Cardona Maria Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1000444797.pdf){:target="_blank"}
* [Murillo Chavera Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1214713668.pdf){:target="_blank"}
* [Navarro Gonzalez Veronica](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1003290622.pdf){:target="_blank"}
* [Noreña Ocampo Jensy Lorena](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1037666245.pdf){:target="_blank"}
* [Serna Garcia Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1001755948.pdf){:target="_blank"}
* [Torres  Lubin Fernando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps71388332.pdf){:target="_blank"}
* [Victoria Florez Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1192779829.pdf){:target="_blank"}
* [Zuleta Cortes Alejandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Ps1001481021.pdf){:target="_blank"}


<h1> Mucha Suerte! </h1>

