---
layout: post
title: "Parcial III"
main-class: 'presentaciones'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Parcial III

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "ParcialIII"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)
```
# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 9:00 am, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
**Recuerden interpretar todos los resultados** en el contexto del enunciado!!!, no hacerlo le va hacer perder punto!!! >:c

* [Acevedo Zapata Alan Orlando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152220366.pdf){:target="_blank"}
* [Arenas Alzate Silvia Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037654737.pdf){:target="_blank"}
* [Argumedo Bedoya Maria](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007822116.pdf){:target="_blank"}
* [Bedoya Martínez Sofía](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1004774415.pdf){:target="_blank"}
* [Bolaños Arias Fabian Mauricio](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037654623.pdf){:target="_blank"}
* [Díaz Sara Melissa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1020453988.pdf){:target="_blank"}
* [García Cano Anny](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152209588.pdf){:target="_blank"}
* [Giraldo Cardona Maria Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007374227.pdf){:target="_blank"}
* [Marín Agudelo Jefferson Arley](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017227638.pdf){:target="_blank"}
* [Martinez Burbano Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1005745532.pdf){:target="_blank"}
* [Martínez Pareja Lilibeth](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1036934721.pdf){:target="_blank"}
* [Mayorga Garcia Diego Alejandro](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007790690.pdf){:target="_blank"}
* [Naranjo Salazar Vanessa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1214747403.pdf){:target="_blank"}
* [Orozco Bedoya Juan David](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1047502478.pdf){:target="_blank"}
* [Osorno Salas Veronica](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152714649.pdf){:target="_blank"}
* [Rodriguez Posada Yuliana Vanessa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1020487230.pdf){:target="_blank"}
* [Serna Garcia Luisa Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001755948.pdf){:target="_blank"}
* [Tobón Cadavid Andrés Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001390571.pdf){:target="_blank"}
* [Torres  Lubin Fernando](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P71388332.pdf){:target="_blank"}
* [Varon Garcia Julian Alfonso](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1113667336.pdf){:target="_blank"}



<h1> Mucha Suerte! </h1>

