---
layout: post
title: "Parcial II"
main-class: 'practica'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: Parcial II

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "ParcialII"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)
```

# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 12:20 am, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>.

* [Cuadros Giraldo Juan Camilo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1152698134.pdf){:target="_blank"}
* [García Cano Anny](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1152209588.pdf){:target="_blank"}
* [Loaiza Orozco Paula Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1047967040.pdf){:target="_blank"}
* [Madrid Rodriguez Cristian Alonso](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1001131866.pdf){:target="_blank"}
* [Marín Agudelo Jefferson Arley](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1017227638.pdf){:target="_blank"}
* [Marín Quiceno Jenny](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P43972762.pdf){:target="_blank"}
* [Mejía Villegas Julian Esteban](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1037610591.pdf){:target="_blank"}
* [Meneses Castaneda Johan Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1017225004.pdf){:target="_blank"}
* [Monsalve Carvajal Kelly Yohana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1007283759.pdf){:target="_blank"}
* [Murillo Chavera Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1214713668.pdf){:target="_blank"}
* [Ochoa Bedoya Jonathan](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1214731158.pdf){:target="_blank"}
* [Ortega Tirado Marcos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1234990979.pdf){:target="_blank"}
* [Osorio Tabares Andrés Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1214729624.pdf){:target="_blank"}
* [Ospina Jaramillo Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1037658895.pdf){:target="_blank"}
* [Ossa Aristizabal Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1214744784.pdf){:target="_blank"}
* [Patiño Bustamante Karen Estefanía](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1001471973.pdf){:target="_blank"}
* [Pineros Pineda Giovanny Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1035440886.pdf){:target="_blank"}
* [Posada Herrera Mariana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1000755725.pdf){:target="_blank"}
* [Ramírez Echeverry Maria Margarita](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1017256589.pdf){:target="_blank"}
* [Rueda Ocampo Maria Fernanda](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1036601343.pdf){:target="_blank"}
* [Sánchez Salgado Manuel José](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1027892154.pdf){:target="_blank"}
* [Serna Palacio Kevin Alexander](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1048020998.pdf){:target="_blank"}
* [Toro Hernández Daniela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1152462186.pdf){:target="_blank"}
* [Valderrama Cardona Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialII/P1017274912.pdf){:target="_blank"}

<h1> Mucha Suerte! </h1>
