---
layout: post
title: "Clase 12"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: |
  Distribuciones de probabilidad discreta: <br>
  - Distribución Binomial Negativa <br>
  - Distribución Poisson <br>
  - Distribución Uniforme discreta <br>
  Teoremas de Aproximación: <br>
  - Aproximación Hipergeométrica a Binomial <br>
  - Aproximación Binomial a Poisson 
  
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase12"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Distribuciones de probabilidad discretas
### Distribución Binomial Negativa
Sea `$X$` el número de ensayos necesarios para generar `$k$` éxitos en un experimento Binomial Negativo, entonces se dice que `$X\sim b^*(k,p)$` si su función de probabilidad es de la forma
`\begin{align*}
p(x) = \left(\begin{array}{c}x-1\\ k-1\end{array}\right)p^k(1-p)^{x-k} \quad \quad x=k, k+1, \ldots
\end{align*}`

#### Teorema
Si `$X\sim b^*(k,p)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=\frac{k}{p} \quad \quad Var(X)=k\frac{(1-p)}{p^2}
\end{align*}`

<button id="Show1" class="btn btn-secondary">Mostrar Ejercicio </button>
<button id="Hide1" class="btn btn-info">Ocultar Ejercicio </button>
<main id="botoncito1"> 
<h3 data-toc-skip> Ejercicio </h3> 
<p>Suponga que por experiencia se sabe que $1$ de cada $5$ personas que solicitan la Visa Americana en la embajada de Estados Unidos en la Ciudad de Bogotá, es rechazada. Basados en lo anterior, </p>
<ol>
<li>Cuál es la probabilidad de que más de $10$ pero a lo más $15$ personas deban solicitar la Visa Americana, para que la Embajada otorgue la octava Visa?.</li>
<li>Cuál es el número promedio y desviación estándar de personas que deben solicitar la Visa Americana hasta que la Embajada de Estados Unidos decida otorgar la décima Visa Americana?</li>
</ol>

<h3 data-toc-skip> Solución </h3> 
<ol>
<li>En este ejercicio, nos piden la probabilidad de que más de $10$ pero a lo más $15$ personas deban presentarse a la embajada de Estados Unidos, hasta que la Embajada decida otorgar la octava Visa Americana, esto es
$$\begin{align*}
\mathbb{P}(10<X\leq 15)
\end{align*}$$

Donde $X$: representa el número de personas que se presentan a la embajada de Estados Unidos para solicitar la Visa, hasta que éstos decidan otorgar la octava Visa. Entonces, como estamos en una situación en la cual nos preguntan por el número de ensayos que hay que realizar, hasta obtener $8$ éxitos, estamos en una situación asociada a una distribución Binomial Negativa, la cual tiene la estructura
$$\begin{align*}
p(x) = \left(\begin{array}{c}x-1\\ k-1\end{array}\right)p^k(1-p)^{x-k} \quad \quad x=k, k+1, \ldots
\end{align*}$$

en donde, $k=8$: representa el número de visas otorgadas por la embajada de Estados Unidos. Entonces como se sabe por experiencia que $1$ de cada $5$ personas que solicitan la Visa es rechazada, se tendrá que a $4$ de cada $5$ personas que solicitan la Visa, se les otorga ésta de forma satisfactoriamente, es decir que al aplicar la definición de frecuencia relativa, tendremos que la proporción $p$, estará dada por
$$\begin{align*}
p &= \frac{\text{# éxitos}}{\text{total Ensayos}} \\
  &= \frac{4}{5} \\
  &= 0.80
\end{align*}$$

Ahora, al emplear la función de distribución Binomial Negativa con $p=0.80$ y $k=8$ tendremos que la probabilidad de interés estará dada por

$$\begin{align*}
\mathbb{P}(10<X\leq 15) &= \sum_{x=11}^{15} \left(\begin{array}{c}x-1\\ 8-1\end{array}\right)(0.80)^8(1-0.80)^{x-8} \\
                        &= \left(\begin{array}{c}11-1\\ 8-1\end{array}\right)(0.80)^8(1-0.80)^{11-8} + \ldots + \left(\begin{array}{c}15-1\\ 8-1\end{array}\right)(0.80)^8(1-0.80)^{15-8} \\
                        &= 0.3179607
\end{align*}$$

En consecuencia, se tendrá un $31.79\%$ de probabilidad, de que más de $10$ pero como máximo $15$ personas deban solicitar la Visa Americana, hasta que la embajada de Estados Unidos decida otorgar la octava Visa.
</li>
<li>En esta ocasión estamos interesados en conocer el promedio y desviación estándar del número de personas que deben presentarse a la embajada de Estados Unidos, hasta que éstos decidan otorgar la octava Visa Americana. Y para ello podemos emplear la formula de la esperanza matemática, de la distribución Binomial negativa, tal que
$$\begin{align*}
\mathbb{E}(X)=\frac{k}{p}
\end{align*}$$

Entonces, como $4$ de $5$ personas que se presentan a la embajada obtienen la Visa, estamos interesados en el octavo éxito, entonces se tendrá que $p=0.80$ y $k=8$, con lo cual obtendremos un número promedio de personas igual a

$$\begin{align*}
\mathbb{E}(X) &= \frac{8}{0.80} \\
              &= 10
\end{align*}$$

Ahora, para calcular la desviación estándar, realizamos primero el cálculo de la varianza para el número de personas que deben presentarse a la embajada, hasta que éstos decidan otorgar la octava visa, tal que
$$\begin{align*}
Var(X) &= k\frac{(1-p)}{p^2} \\
       &= 8\left(\frac{1-0.8}{0.8^2}\right) \\
       &= 8(0.3125) \\
       &= 2.5
\end{align*}$$
y basados en este resultado, procedemos con el cálculo de la desviación estándar, mediante la ecuación
$$\begin{align*}
Sd(X) &= \sqrt{Var(X)} \\
      &= \sqrt{2.5} \\
      &= 0.559017
\end{align*}$$


De lo anterior se tiene que en promedio deberán presentarse $10$ personas a la embajada Americana, con una desviación estándar de $0.559017$, para que estos otorguen $8$ Visas. 
</li>
</ol>
</main>

### Proceso Poisson
Un proceso Poisson es aquel que cumple

1. El número de resultados que ocurren en un intervalo o región específica es independiente del número que ocurre en cualquier otro intervalo de tiempo o región del espacio disjunto.
2. La probabilidad de que ocurra un solo resultado durante un intervalo de tiempo corto o región pequeña es proporcional a la longitud del intervalo o al tamaño de la región, y no depende del número de resultados que ocurren por fuera de este intervalo de tiempo o región.
3. La probabilidad de que ocurra más de un resultado en tal intervalo o región pequeña es insignificante.



### Distribución Poisson
El número de sucesos que ocurren en un intervalo de tiempo o región específica, es una variable aleatoria `$X$` con distribución de probabilidad Poisson, tal que
`\begin{align*}
f(x) = \frac{e^{-\lambda}\lambda^x}{x!} \quad \quad x=0,1,\ldots
\end{align*}`
donde `$\lambda$` es el parámetro de la distribución y representa el número promedio de sucesos por unidad de tiempo o región específica.

#### Teorema
Si `$X\sim P(\lambda)$` entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=\lambda \quad \quad Var(X)=\lambda
\end{align*}`

<button id="Show3" class="btn btn-secondary">Mostrar Ejercicio </button>
<button id="Hide3" class="btn btn-info">Ocultar Ejercicio </button>
<main id="botoncito3"> 
<h3 data-toc-skip> Ejercicio </h3> 
<p> Los huecos en las carreteras pueden ser un problema grave y requieren de reparación constante con un tipo específico de mezcla de concreto. La experiencia sugiere que hay en promedio $1.5$ huecos por cada dos kilómetros recorridos, después de cierta cantidad de uso. Si se supone que $X$ representa el número de huecos que hay en la carretera
<ol>
<li>Cuál es la probabilidad de que no aparezca más de un hueco en la carretera en un tramo de dos kilómetros? </li> 
<li>Cuál es la probabilidad de que aparezca más de hueco en un tramo de un kilómetro?</li>
<li>Cuál es el número promedio y desviación estándar del número de huecos que se encuentran en $5$ kilómetros?.</li>
</ol>
</p>

<h3 data-toc-skip> Solución </h3> 
<p>En este caso nos dicen que nuestra variable aleatorias es $X$ el número de huecos que se encuentran en la carretera, y que en promedio se encuentran $1.5$ huecos cada dos kilómetros.
</p>
<ol>
<li>Basados en lo anterior, nos preguntan por la probabilidad de que no aparezca más de un hueco en la carretera en un tramo de dos kilómetros. Es decir, nos preguntan por la probabilidad de que aparezca como máximo $1$ hueco en la carretera en un tramo de dos kilómetros. En este caso se tendrá la siguiente probabilidad
$$\begin{align*}
P(X\leq 1) &= \sum_{x=0}^1 \frac{e^{-1.5}1.5^x}{x!} \\
           &= \frac{e^{-1.5}1.5^0}{0!} + \frac{e^{-1.5}1.5^1}{1!} \\\\
           &= 0.2231302 + 0.3346952 \\
           &= 0.5578254
\end{align*}$$
Es decir, la probabilidad de que no aparezca más de un hueco en la carretera en el tramo de dos kilómetros es del $55.78\%$.
</li>
<li>Ahora, se tiene interés en conocer la probabilidad de que aparezca más de un hueco en un tramo de un kilómetro. En este caso debe notarse que se cambió la unidad de medida, en donde en lugar de dos kilómetros se habla de un kilómetro.<br>
<br>
Debido a ésto, será necesario actualizar nuestro parámetro $\lambda$ mediante el empleo de una regla de $3$, de la siguiente manera.
$$\begin{align*}
 2_{\text{km}} &- 1.5_{\text{huecos}} \\
 1_{\text{km}} &- \lambda
\end{align*}$$
esto es,
$$\begin{align*}
 \lambda &= \frac{1.5_{\text{huecos}} \times 1_{\text{km}}}{2_{\text{km}}} \\
 \lambda &= 0.75_{\text{huecos}}
\end{align*}$$
Es decir, que en un tramo de un kilómetro ocurren $0.75$ huecos en promedio. Conocido el valor del parámetro $\lambda$ para el tramo de un kilómetro, se procede a calcular la probabilidad de que aparezca más de un hueco en el tramo de un kilómetro, tal que
$$\begin{align*}
 \mathbb{P}(X>1) = \sum_{x=2}^\infty \frac{e^{-0.75}0.75^x}{x!} \\
\end{align*}$$
En donde se aprecia que es una suma infinita, y en consecuencia se procede a trabajar tal probabilidad por su complemento.
$$\begin{align*}
 \mathbb{P}(X>1) &= 1 - \mathbb{P}(X\leq1)  \\
                 &= 1 - \sum_{x=0}^1 \frac{e^{-0.75}0.75^x}{x!} \\
                 &= 1 - \frac{e^{-0.75}0.75^0}{0!} - \frac{e^{-0.75}0.75^1}{1!} \\
                 &= 1 - 0.4723666 - 0.3542749 \\
                 &= 0.1733585
\end{align*}$$

Es decir que, la probabilidad de que se encuentre más de $1$ hueco en un tramo de $1$ kilómetro cuando se viaja por carretera, es del $17.33\%$.
</li>
<li>Finalmente, se tiene interés en conocer cual será el promedio y desviación estándar, del número de huecos que se encontrarán en la carretera en el tramo de $5$ kilómetro. En este caso, como se cambia la unidad de medida de $2$ kilómetros a $5$ kilómetros, será necesario recalcular el valor de $\lambda$, ta que

$$\begin{align*}
 2_{\text{km}} &- 1.5_{\text{huecos}} \\
 5_{\text{km}} &- \lambda
\end{align*}$$
esto es,
$$\begin{align*}
 \lambda &= \frac{1.5_{\text{huecos}} \times 5_{\text{km}}}{2_{\text{km}}} \\
 \lambda &= 3.75_{\text{huecos}}
\end{align*}$$


Ahora, al aplicar la formular de esperanza matemática para la distribución Poisson, se tiene que el número esperado de huecos en $5$ kilómetros es de
$$\begin{align*}
\mathbb{E}(X) & = \lambda \\
              & = 3.75\\
\end{align*}$$

Similarmente, se procede a realizar el cálculo de la varianza para poder calcular la desviación estándar, del número de huecos que hay en un tramo de $5$ kilómetros
$$\begin{align*}
Var(X) &= \lambda \\
       &= 3.75\\
\end{align*}$$
y con este valor, se procede a calcular la desviación estándar
$$\begin{align*}
Sd(X) &= \sqrt{Var(X)} \\
      &= \sqrt{Var(3.75)} \\
Sd(X) & = 1.936492
\end{align*}$$
De lo anterior se tiene que, en el tramo de $5$ kilómetros de carretera, se espera encontrar $3.75$ huecos, con una desviación estándar de $1.93$ huecos.
</li>
</ol>
</main>


### Distribución Uniforme discreta
Se dice que la variable aleatoria `$X$`tiene una distribución uniforme discreta en los enteros `$1,2,\ldots, m$`, si su distribución de probabilidad es de la forma
`\begin{align*}
f(x) = \frac{1}{m} \quad \quad x = 1,2, \ldots, m
\end{align*}`

#### Teorema
Si `$X\sim Unif{1,2,\ldots,m}.$` entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=\frac{m+1}{2} \quad \quad Var(X)=\frac{m^2-1}{12}
\end{align*}`

<!-- Demostración, suma de números triangulares pitágoras -->
<!-- `\begin{align*} -->
<!-- \sum_{i=1}^N x_i = \frac{N(N+1)}{2} \quad \quad \sum_{i=1}^N x_i^2 = \frac{N(N+1)(2N+1)}{6} -->
<!-- \end{align*}` -->

## Teoremas de Aproximación
### Teorema de Aproximación Hipergeométrica a Binomial
Si `$X\sim h(N,M,n)$` con `$n$` pequeña en comparación con `$N$` (`$n/N <0.05$`) entonces se dice que `$X\stackrel{a}{\sim}b(n,p)$` con `$p = M/N$`.

### Teorema de Aproximación Binomial a Poisson
Si `$X\sim b(n,p)$` con `$n$` grande `$(n\geq 100)$` y `$p$` pequeña `$(p\leq 0.01)$` entonces se dice que `$X\stackrel{a}{\sim}P(\lambda)$` donde `$\lambda = np$`
