---
layout: post
title: "Clase 11"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: |
  Distribuciones de probabilidad discreta: </br>
  - Distribución Binomial </br>
  - Distribución Hipergeométrica </br>
  - Distribución Geométrica
  
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase11"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Distribuciones de probabilidad discretas
### Proceso Bernoulli
Un proceso Bernoulli es aquel que cumple

1. El experimento consta de ensayos repetidos.
2. Cada ensayo produce un resultado que se puede clasificar como éxito o fracaso.
3. La probabilidad de éxito se denota por `$p$`, mientras que la probabilidad de fracaso se denota por `$q=1-p$`, y estas probabilidades permanecen constante de un ensayo a otro.
4. Los ensayos repetidos son independientes.

<button id="Show1" class="btn btn-secondary">Mostrar Ejemplo </button>
<button id="Hide1" class="btn btn-info">Ocultar Ejemplo </button>
<main id="botoncito1"> 
<h3 data-toc-skip> Ejemplo </h3> 
<p> Los siguientes, son algunos ejemplos de casos que pueden considerarse como Procesos Bernoulli, debido a que cumplen las $4$ condiciones propuestas anteriormente.</p>
<ul>
<li>Tirar una moneda al aire y observar si sale cara o sello.</li>
<li>Mirar el próximo carro que pasa por debajo de un puente, y observar si es o no de color azul.</li>
<li>Comprar una empanada y determinar si tiene buen sabor o mal sabor.</li>
<li>Seleccionar un estudiante de la Universidad, y determinar si éste nació o no en Antioquia.</li>
</ul>
</main>

### Ensayo de Bernoulli
Si la probabilidad de éxito de un experimento es `$p$`, entonces se tendrá que la probabilidad de fallo será `$1-p$`, y por tanto, la función de probabilidad de la variable aleatoria `$X\sim Be(p)$` de un ensayo Bernoulli es
`\begin{align*}
f(x) = p^x(1-p)^{1-x} \quad \quad x=0,1
\end{align*}`

#### Teorema
Si `$X\sim Be(p)$`, entonces se puede probar que la media y la varianza de la variable aleatoria `$X$` están dadas por 
`\begin{align*}
\mathbb{E}(X)=p \quad \quad Var(X)=p(1-p)
\end{align*}`

<button id="Show2" class="btn btn-secondary">Mostrar Ejercicio </button>
<button id="Hide2" class="btn btn-info">Ocultar Ejercicio </button>
<main id="botoncito2"> 
<h3 data-toc-skip> Ejercicio </h3> 
<p> Suponga que en un estudio se encontró que $2$ de cada $5$ estudiantes no desea tomar clases virtuales. Si se selecciona aleatoriamente un estudiante, cuál es la probabilidad de que éste desee tomar clases virtuales, y determine su media y desviación estándar.</p>

<h3 data-toc-skip> Solución </h3> 
<p>En este caso estamos interesados en la variable $X$, que representa el número de estudiantes que desean tomar clases virtuales, en donde sabemos que si, $2$ de cada $5$ no quieren tomar clases virtuales, entonces se tendrá que $3$ de cada $5$ si desean tomar clases virtuales. Por tanto al aplicar la definición de frecuencia relativa se tiene que 

$$\begin{align*}
p &= \frac{\text{Número de éxitos}}{\text{Número de muestras}} \\
  &= \frac{3}{5} \\
  &= 0.6
\end{align*}$$
siendo $p$ la probabilidad de que un estudiante desee tomar clases virtuales.

Ahora, la probabilidad de que se seleccione un estudiante al azar, y éste desee tomar clases virtuales será
$$\begin{align*}
\mathbb{P}(X = 1) &= p(1-p)^{1-x} \\
                  &= 0.6(0.4)^{1-1} \\
                  &= 0.6(0.4)^0 \\
                  &= 0.6
\end{align*}$$

es decir, que la probabilidad de que el estudiante seleccionado desee tomar clases virtuales será del $60\%$.

Ahora, para calcular la desviación estándar se requiere calcular inicialmente la varianza de la variable aleatoria, la cual está dada por 
$$\begin{align*}
Var(X) &= p(1-p) \\
       &= 0.6(0.4) \\
       &= 0.24
\end{align*}$$

y a partir de éste valor, se tendrá que la desviación estándar es igual a 
$$\begin{align*}
Sd(X) &= \sqrt{Var(X)} \\
      &= \sqrt{0.24} \\
      &= 0.4898979
\end{align*}$$
Entonces, como el valor esperado de un proceso Bernoulli es igual a $p$, esto es
$$\begin{align*}
\mathbb{E}(X) &= p \\
              &= 0.6
\end{align*}$$
Por tanto, al seleccionar un solo estudiante, se espera que $0.6$ estudiantes respondan que desean tomar clases virtuales, con una desviación estándar de $0.489$.
</p>
</main>

### Distribución Binomial
Si `$X$` es la variable aleatoria del número de éxitos de `$n$` ensayos de Bernoulli, con probabilidad de éxito `$p$`, entonces se dice que `$X\sim b(n,p)$` tal que
`\begin{align*}
f(x) = \left(\begin{array}{c}n\\ x\end{array}\right)p^x(1-p)^{n-x} \quad \quad x=0,1,\ldots,n
\end{align*}`

**Nota:** Esta distribución es usada cuando se realiza muestreo **con reemplazo** o en poblaciones infinitas en donde es posible **suponer que la probabilidad de éxito `$p$` es la misma** en cada ensayo Bernoulli.

#### Teorema
Si `$X\sim b(n,p)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=np \quad \quad Var(X)=np(1-p)
\end{align*}`

<button id="Show3" class="btn btn-secondary">Mostrar Ejercicio </button>
<button id="Hide3" class="btn btn-info">Ocultar Ejercicio </button>
<main id="botoncito3"> 
<h3 data-toc-skip> Ejercicio </h3> 
<p> Suponga que en un estudio se encontró que $2$ de cada $5$ estudiantes no desea tomar clases virtuales. Si se selecciona aleatoriamente $20$ estudiantes, calcule
<ol>
<li>Cuál es la probabilidad de que no más de $3$ estudiantes deseen tomar clases virtuales?</li> 
<li>Cuál es la probabilidad de que no menos de $6$ pero menos de $12$ deseen tomar clases virtuales?</li>
<li>Cuál es el número promedio y desviación estándar del número de estudiantes que desean tomar clases virtuales?.</li>
</ol>
</p>

<h3 data-toc-skip> Solución </h3> 
<p>En este caso estamos interesados en la variable $X$, que representa el número de estudiantes que desean tomar clases virtuales, en donde sabemos que si, $2$ de cada $5$ no quieren tomar clases virtuales, entonces se tendrá que $3$ de cada $5$ si desean tomar clases virtuales. Por tanto al aplicar la definición de frecuencia relativa se tiene que 

$$\begin{align*}
p &= \frac{\text{Número de éxitos}}{\text{Número de muestras}} \\
  &= \frac{3}{5}\\ 
  &= 0.6
\end{align*}$$
siendo $p$ la probabilidad de que un estudiante desee tomar clases virtuales.
</p>
<ol>
<li>En este caso, estamos interesados en calcular la probabilidad de que no más de $3$ estudiantes deseen tomar clases virtuales, lo cual puede representarse mediante la siguiente probabilidad
$$\begin{align*}
P(X\leq 3) &= \sum_{x=0}^3 \left(\begin{array}{c}20\\ x\end{array}\right)0.6^x(1-0.6)^{20-x} \\
           &= \left(\begin{array}{c}20\\ 0\end{array}\right)0.6^0(0.4)^{20-0} + \ldots + \left(\begin{array}{c}20\\ 3\end{array}\right)0.6^3(0.4)^{20-3} \\
           &= 0.00000001099512 + 0.0000003298535 + 0.000004700412 + 0.00004230371 \\
           &= 0.00004734497
\end{align*}$$
Es decir, la probabilidad de que como máximo $3$ estudiantes de los $20$ seleccionados, deseen tomar clases virtuales, es del $0.0047\%$.
</li>
<li>Ahora, se tiene interés en conocer la probabilidad de que no menos de $6$ pero menos de $12$ deseen tomar clases virtuales. En este caso, la probabilidad asociada puede calcularse de la siguiente manera.
$$\begin{align*}
P(6 \leq x < 12) &= \sum_{x=6}^{11} \left(\begin{array}{c}20\\ x\end{array}\right)0.6^x(1-0.6)^{20-x} \\
           &= \left(\begin{array}{c}20\\ 6\end{array}\right)0.6^6(0.4)^{20-6} + \ldots + \left(\begin{array}{c}20\\ 11\end{array}\right)0.6^{11}(0.4)^{20-11} \\
           &= 0.4027898
\end{align*}$$
Es decir que, la probabilidad de que como mínimo $6$ pero menos de $12$ estudiantes deseen tomar clases virtuales de los $20$ seleccionados, es del $40.28\%$.
</li>
<li>Finalmente, se tiene interés en conocer cual será el número promedio y desviación estándar, de estudiantes que desean tomar clases virtuales, cuando se realiza la selección aleatoria de $20$. Al aplicar la formular de esperanza matemática para la distribución binomial, se tiene que el valor esperado de estudiantes que desean tomar clases virtuales es de
$$\begin{align*}
\mathbb{E}(X) & = np \\
              & = 20(0.6)\\
              & = 12
\end{align*}$$

Se procede a realizar el cálculo de la varianza para poder calcular la desviación estándar, del número de estudiantes que desean tomar clases virtuales, tal que
$$\begin{align*}
Var(X) &= np(1-p) \\
       &= 20(0.6)(1-0.6)\\
       & = 4.8
\end{align*}$$
y con este valor, se procede a calcular la desviación estándar
$$\begin{align*}
Sd(X) &= \sqrt{Var(X)} \\
      &= \sqrt{Var(4.8)} \\
      & = 2.19089
\end{align*}$$
De lo anterior se tiene que, al realizar la selección aleatoria de $20$ estudiantes, es espera que $12$ estudiantes desean tomar clases virtuales, con una desviación estándar de $2.19$ estudiantes.
</li>
</ol>
</main>

### Distribución Hipergeométrica
Si `$X$` es el número de éxitos de una muestra completamente aleatoria de tamaño `$n$` extraída de una población `$N$` compuesta por `$M$` éxitos y `$(N-M)$` fracasos, entonces la distribución de probabilidad de `$X$`, denotada por `$h(N,M,n)$`, está dado por 
`\begin{align*}
h(N,M,n)=\frac{\left(\begin{array}{c}M\\ x\end{array}\right) \left(\begin{array}{c}N-M\\ n-x\end{array}\right)}{\left(\begin{array}{c}N\\ n\end{array}\right)}
\end{align*}`

con `$x$` un entero que satisface la condición `$\max\{0, M-(N-n)\} \leq x \leq \min\{M,n\}$`.

**Nota:** Esta distribución es usada cuando se realiza muestreo **sin reemplazo**, en poblaciones finitas donde hay `$M$` éxitos de un total de `$N$` objetos, de los cuales se seleccionan `$n$` objetos a la vez.

#### Teorema
Si `$X\sim h(N,M,n)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=n\frac{M}{N} \quad \quad Var(X)=\left(\frac{N-n}{N-1}\right)\left(\frac{M}{N}\right)\left(1-\frac{M}{N}\right)
\end{align*}`

### Experimento Binomial Negativo
Consideremos un experimento con las mismas propiedades de un experimento binomial, solo que en este caso, las pruebas se repetirán hasta que ocurra un número fijo de éxitos. Por lo tanto en vez de encontrar la probabilidad de `$X$` éxitos en `$n$` pruebas, donde `$n$` es fija, ahora nos interesa la probabilidad de que ocurra el `$k$`-ésimo éxito en la `$X$`-ésima prueba.

### Distribución Geométrica
Sea  `$X$` el número de ensayos necesarios para generar un éxito (`$k=1$`), entonces se dice que `$X\sim g(p)$` si su función de probabilidad es de la forma
`\begin{align*}
g(p) = p(1-p)^{x-1} \quad \quad x = 1,2,\ldots
\end{align*}`

#### Teorema
Si `$X\sim g(p)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X)=\frac{1}{p} \quad \quad Var(X)=\frac{1-p}{p^2}
\end{align*}`
