---
layout: post
title: "Clase 07"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: |
  Introducción a variables aleatorias <br/>
  Distribuciones de probabilidad discretas <br/>
  Distribuciones de probabilidad continua <br/>
  Función de distribución acumulada
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase07"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Variables aleatorias
Es una función que asocia un número real a cada elemento del espacio muestral `$S$`. Comúnmente las variables aleatorias se denotan por letras mayúsculas del final del alfabeto `$(X,Y,Z)$` y a los valores observados por letras minúsculas `$(x,y,z)$`.

Las variables aleatorias se pueden clasificar en tres tipos

* **Variables Bernoulli:** Cualquier variable aleatoria cuyos posibles valores sean 0 o 1.
* **Variables discretas:** Son aquellas que tienen un número finito de posibilidades o una serie interminable de elementos como números enteros existentes (es enumerable).
* **Variables continuas:** Son aquellas que contienen un número infinito de posibilidades, o igual número de puntos que un segmento de recta.

<button id="Show1" class="btn btn-secondary">Mostrar Ejercicio </button>
<button id="Hide1" class="btn btn-info">Ocultar Ejercicio </button>
<main id="botoncito1"> 
<h3 data-toc-skip> Ejercicio </h3> 
<p> Identifique el tipo de variables aleatorias y asigne un valor numérico a los elementos del espacio muestral.</p>
<ol>
<li> El número de lanzamientos de un dado hasta que caiga un $4$</li>
<li> La proporción de estudiantes que se encuentran enfermas, en la Facultad de Ciencias Económicas </li>
<li> Toma un artículo de una banda de ensamble y verificar si éste se encuentra o no defectuoso.</li>
</ol>

<h3 data-toc-skip> Solución </h3> 
<ol>
<li> Si llamamos a $F$ al evento de obtener un número diferente a $4$ y a $E$ al evento de obtener un $4$, entonces observamos que al lanzar el dado, el número $4$ puede caer en el primer lanzamiento, o en el segundo, o en el tercero, etc, etc, y por tanto el espacio muestral estará dado por 
$$\begin{align*}
S:\{E, FE, FFE, FFFE, \ldots\}
\end{align*}$$
y en consecuencia, podemos definir la <strong>variable aleatoria discreta $X$ </strong> con los números $1$, $2$, $3$, $\ldots$, al número de lanzamientos necesarios hasta obtener un $4$. Es decir, la variable aleatoria tendrá dominio en
$$\begin{align*}
X=1, 2, 3, \ldots
\end{align*}$$
</li>
<li>Dado que es una proporción, entonces el espacio muestral puede ser cualquier valor que se encuentre entre $0$ y $1$, entonces tendrémos a <strong>$Y$, una variable aleatoria continua </strong> con dominio definido en
$$\begin{align*}
0\leq Y\leq 1
\end{align*}$$
</li>
<li>El ejercicio consta en elegir un artículo de una banda de ensamble y comprobar si tiene o no defectos, y por tanto, el espacio muestral tendrá dos puntos, $D$ si el artículo está defectuoso, y $N$ si el artículo no está defectuoso, tal que
$$\begin{align*}
S:\{D,N\}
\end{align*}$$
Entonces, como solo pueden haber dos posibilidades, defectuoso y no defectuoso, podemos definir una variable aleatoria Bernoulli $Z$, la cual se definirá como
$$\begin{align*}
Z = \begin{cases}
0 & \text{ Si el artículo está defectuoso } \\
1 & \text{ Si el artículo no está defectuoso }
\end{cases}
\end{align*}$$
</li>
</ol>
</main>

## Distribución de probabilidad discreta

Se dice que el conjunto de pares ordenados `$(x,p(x))$` es una función de masa de probabilidad (*fmp*) de la variable aleatoria discreta `$X$`, si para cualquier resultado posible de `$X$` se cumple que

1. `$p(x)\geq0$` para todo `$x \in$` al rango de `$X$`
2. `$\sum_x p(x)=1$`
3. `$\mathbb{P}(X\in A)= \sum_{x\in A}p(x) $` con `$A$` un rango de valores `$\in$` al rango de `$X$`.

## Función de distribución acumulada caso discreto

La función de distribución acumulada (*fda*) denotada por `$F(x)$`, para una variable aleatoria discreta `$X$` con distribución de probabilidad `$p(x)$` es de la forma 
`\begin{align*}
F(x)=P(X\leq x)=\sum_{t\leq x}p(t) \quad \quad -\infty<x<\infty
\end{align*}`

para cualquier `$x$` dentro del rango de `$X$`, `$F(x)$` será la suma acumulada de todos los valores de rango de `$X$` menores a `$x$`.

## Distribución de probabilidad continua
La función `$f(x)$` es una función de densidad de probabilidad (*fdp*) para la variable aleatoria continua `$X$`, definida en el conjunto de números reales, si

1. `$f(x)\geq0$` para todo `$x\in \mathbb R$`
2. `$\int_{-\infty}^\infty f(x)dx=1$`
3. `$P(a<x<b) = \int_a^b f(x)dx$` con `$a$` y `$b$` dos constantes `$\in \mathbb{R}$`

## Función de distribución acumulada caso continuo

La función de distribución acumulada (*fda*) denotada por `$F(x)$`, para una variable aleatoria continua `$X$` con distribución de densidad de probabilidad `$f(x)$` es de la forma 
`\begin{align*}
F(x)=P(X\leq x)=\int_{-\infty}^x f(t)dt \quad \quad -\infty<x<\infty
\end{align*}`
para cualquier `$x$`, `$F(x)$` es el área bajo la curva de densidad a la izquierda de valor que tome `$x$`.
