---
layout: post
title: "Práctica 04"
main-class: 'practica'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Ejercicio sobre variables aleatorias y distribuciones de probabilidad.
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Práctica04"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

## Lista de ejercicios

1. Se encuentra que la concentración promedio de zinc que se obtiene en una muestra de mediciones en `$36$` sitios diferentes de un río es de `$2.6$` gramos por mililitro. Si la función de probabilidad es conocida, pero se sabe su desviación estándar es de `$0.3$` gramos por mililitro. Basado en lo anterior
<ol type ="a">
  <li> Calcule la probabilidad de que la concentración media de zinc en el río se encuentre entre $2.2$ y $2.3$ gramos por mililitro.
  </li>
  <li> Calcule un intervalo de confianza del $95\%$ para la concentración media de zinc en el río?
  </li>
</ol>
2. ¿Qué tan grande debe ser el tamaño muestral del punto anterior si queremos tener `$95\%$` de confianza en que nuestra estimación de la media poblacional diferirá por menos de `$0.05$`?
3. En una empresa se deciden comparar la resistencia de dos clases de hilo, y para ello se prueban `$50$` piezas de cada clase de hilo en condiciones similares, encontrando que, la marca `$A$` tiene una resistencia promedio a la tensión de `$78.3$` kilogramos, con una desviación estándar de `$5.6$` kilogramos; en tanto que la marca `$B$` tiene una resistencia promedio a la tensión de `$87.2$` kilogramos con una desviación estándar de `$6.3$` kilogramos. Construya un intervalo de confianza del `$95\%$` entre la diferencia de las resistencias promedio de tensión de los hilos. Es posible pensar que la resistencia promedio a la tensión de la marca `$A$` es menor que la resistencia promedio a la tensión de la marca `$B$`?
4. Suponga que el contenido de ácido sulfúrico, en litros, de una muestra aleatoria de `$7$` contenedores similares es de 
`\begin{align*}
9.8 \quad 10.2 \quad 10.4 \quad 9.8 \quad 10.0 \quad 10.2 \quad 9.6
\end{align*}`
Construya un intervalo de confianza del `$95\%$` para el contenido promedio de todos los contenedores suponiendo que el contenido de los contenedores se distribuye aproximadamente normal.
5. Para un experimento de pruebas psicológicas se seleccionan al azar `$25$` sujetos de prueba y se les mide sus tiempos de reacción, en segundos, ante un estímulo particular, obteniendo que el tiempo promedio de reacción de los sujetos es de `$6.2$` segundos. La experiencia sugiere que la varianza en los tiempos de reacción ante los diferentes tipos de estímulos es de `$4_{s^2}$` y que la distribución de probabilidad para los tiempos de reacción es aproximadamente normal. Basado en lo anterior
<ol type ="a">
  <li> Calcule la probabilidad de el tiempo de reacción promedio para todos los individuos sea a lo más de $6$ segundos.
  </li>
  <li> Calcule el límite superior del $95\%$ para el tiempo medio de reacción de todos los individuos.
  </li>
</ol>
6. Un investigador de la \texttt{ucla} afirma que la esperanza de vida de los ratones se puede extender hasta en `$25\%$` cuando se reduce aproximadamente `$40\%$` de las calorías de su dieta desde el momento en que son destetados, en donde, la dieta restringida se enriquece hasta niveles normales con vitaminas y proteínas. Si se supone que a partir de estudios previos se sabe que la desviación estándar del aumento de vida de los ratones es de `$5.8$` meses, ¿cuántos ratones se deberían incluir en la muestra para tener un `$99\%$` de confianza en que la vida media esperada de la muestra estará dentro de 2 meses a partir de la media de la población para todos los ratones sujetos a la dieta reducida?
7. Suponga que el grupo ALIADO, realiza un estudio sobre la altura que poseen los estudiantes de la Universidad, y para ello, toma una muestra aleatoria de `$50$` estudiantes universitarios y encuentra que la estatura promedio fue de `$174.5$` centímetros con una desviación estándar de `$6.9$` centímetros. Basados en la información anterior,
<ol type ="a">
  <li> Construya un intervalo de confianza del $98\%$ para la estatura media de todos los estudiantes universitarios.
  </li>
  <li> ¿Qué podemos afirmar con una confianza del $98\%$ acerca del posible tamaño de nuestro error, si estimamos que la estatura media de todos los estudiantes universitarios es de $174.5$ centímetros?
  </li>
  <li> Cual es la probabilidad de que la estatura promedio de todos los estudiantes sea a lo sumo $172$ centímetros, si suponemos que las alturas se distribuyen <i>iid</i> con desviación estándar de $7.3$ centímetros.
  </li>
8. Dos marcas de refrigeradores, denotadas por `$A$` y `$B$` poseen garantías de `$1$` año. Suponga que en una muestra aleatoria de `$50$` refrigeradores de la marca `$A$`, se observó que `$12$` de ellos fallaron antes de terminar el periodo de garantía, mientras que, una muestra aleatoria independiente de `$60$` refrigeradores de la marca `$B$` también reveló que `$12$` de ellos fallaron durante el período de garantía. 
<ol type ="a">
  <li> Calcule con un nivel de confianza del $98\%$ un intervalo de confianza para la diferencia entre las proporciones de falla, dentro del periodo de garantía, para todos los refrigeradores de las marcas $A$ y $B$.</li>
  <li> ¿Podría concluirse que hay evidencia suficiente para afirma que existen diferencia significativas entre las proporciones de fallas, dentro del período de garantía, para las dos marcas de refrigeradores? ¿Por qué?</li> 
</ol>
9. ¿Está menguando el romance de los estadounidenses con el cine?, En una encuesta realizada por la empresa Gallup a `$800$` adultos seleccionados de forma aleatoria, se encontró que `$45\%$` de los encuestados indicaron que el cine estaba mejorando, mientras que, `$43\%$` de los encuestados dijeron que el cine estaba empeorando. Basados en lo anterior
<ol type ="a">
  <li>  Encuentre un intervalo de confianza de $87\%$ para la proporción total de de adultos que piensan que el cine está mejorando.</li>
  <li>¿El intervalo incluye el valor $p = 0.50$? ¿Piensa usted que la mayoría de los adultos piensa que el cine está mejorando?</li>
</ol>
10. Los administradores de un hospital deseaban estimar el número promedio de días necesarios para el tratamiento de enfermos internados entre las edades de `$25$` y `$34$` años. Una muestra aleatoria de `$500$` pacientes entre estas edades produjo una media y una desviación estándar igual a `$5.4$` y `$3.1$` días, respectivamente. Basado en la información anterior, 
<ol type ="a">
  <li> Calcule la probabilidad de que la varianza de la población de pacientes de la cual se extrajo la muestra, tenga un valor superior a $8_{días^2}$ .
  </li>
  <li> Calcule el límite superior de un intervalo de confianza del $95\%$ para la duración media de permanencia de la población de pacientes de la cual se extrajo la muestra.	
  </li>
</ol>
11. A la mayoría de estadounidenses les gusta participar en eventos deportivos o al menos verlos. Algunos sienten que los deportes tienen más que sólo valor de entretenimiento, tanto así, que en una encuesta realizada a `$1000$` adultos, realizada por KRC Research \& Consulting, se encontró que `$78\%$` sintieron que los deportes de gran atractivo tienen un efecto positivo en la sociedad.
<ol type ="a">
  <li> Encuentre un intervalo de confianza de $95\%$ para el porcentaje del público que piensa que los deportes tienen un efecto positivo en la sociedad.
  </li>
  <li> La encuesta publicó un margen de error de “más o menos $3.1\%$”. ¿Esto concuerda con la respuesta encontrada en el inciso a)? ¿Qué valor de $p$ produce el margen de error dado por la encuesta?
	</li>
</ol>
12. Para una comparación de los porcentajes de piezas defectuosas producidas por dos líneas de montaje, de cada línea se seleccionaron muestras aleatorias independientes de `$100$` piezas. La línea `$A$` produjo `$18$` piezas defectuosas en la muestra y la línea B contenía `$12$` piezas defectuosas. 
<ol type ="a">
  <li> Encuentre un intervalo de confianza de $98\%$ para la verdadera diferencia en proporciones de piezas defectuosas para las dos líneas.
  </li>
  <li> ¿Hay evidencia aquí que sugiera que una línea produce una proporción más alta de piezas defectuosas que la otra?
  </li>
</ol>
13. Es frecuente que encuestadores por teléfono entrevisten entre `$1000$` y `$1500$` personas sobre sus opiniones en asuntos varios. En este caso tienen interés en ¿El rendimiento de los equipos de atletismo universitarios tiene un impacto positivo en la percepción del público del prestigio de las instituciones?. Y por ello, se realizará una nueva encuesta para ver si hay diferencia entre las opiniones de hombres y mujeres sobre este asunto.
<ol type ="a">
  <li> Si se han de entrevistar $1000$ hombres y $1000$ mujeres, ¿con cuánta precisión podría usted estimar la diferencia en las proporciones que piensan que el rendimiento de sus equipos de atletismo tiene un impacto positivo en la percepción del público acerca del prestigio de las instituciones? Encuentre un límite para el error de estimación.	
  </li>
  <li> Supongamos que usted estuviera diseñando la encuesta y desea estimar la diferencia en un par de proporciones, correcta a no más de $0.02$, con probabilidad $0.9$. ¿Cuántas entrevistas deben incluirse en cada muestra si suponemos que éstas son iguales? 
  </li>
</ol>
14. Las calificaciones del Examen de Evaluación Escolar (SAT por sus siglas en inglés), que han bajado lentamente desde el inicio del examen, ahora han empezado a subir. Originalmente, una calificación de `$500$` estaba considerada como promedio. Las calificaciones medias para el `$2005$` fueron aproximadamente `$508$` para el examen verbal y `$520$` para el examen de matemáticas. Una muestra aleatoria de las calificaciones del examen, de `$20$` alumnos de último año de una preparatoria urbana de gran tamaño, produjo las medias y desviaciones estándar citadas en la tabla siguiente
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Verbal</td>
    <td style="font-weight: bold">Matemáticas</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>505</td>
    <td>495</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>57</td>
    <td>69</td>
  </tr>
</tbody>
</table>
</pre>
<ol type ="a">
  <li> Encuentre un intervalo de confianza de $90\%$ para la media de calificaciones del SAT verbal para alumnos de último año de preparatoria urbana.
  </li>
  <li> ¿El intervalo hallado por usted en el inciso a) incluye el valor $508$?, la calificación media real del SAT verbal para $2005$? ¿Qué puede concluir?
  </li>
  <li> Construya un intervalo de confianza de $90\%$ para la calificación media del SAT de matemáticas para alumnos de último año de preparatoria urbana. ¿El intervalo incluye $520$, la calificación media real de matemáticas para $2005$? ¿Qué puede concluir?
  </li>
</ol>
15. Se está considerando un nuevo sistema de lanzamiento de cohetes para el despliegue de cohetes pequeños, de corto alcance. Suponga que por experiencia, se sabe que la probabilidad de que el sistema existente tenga un lanzamiento exitoso es del `$80\%$`. Si se toma una muestra de `$40$` lanzamientos experimentales con el nuevo sistema y `$34$` resultan exitosos.
<ol type ="a">
  <li> Construya un intervalo de confianza del $95\%$ para $p$. 
  </li>
  <li> ¿Con base en sus resultados, concluiría que el nuevo sistema es mejor?
  </li>
</ol>
16. Es frecuente que los químicos orgánicos purifiquen compuestos orgánicos por medio de un método conocido como cristalización fraccional. Un experimentador desea preparar y purificar `$4.85$` gramos de anilina. Diez especímenes de `$4.85$` gramos de anilina se prepararon y purificaron para producir acetanilida. Se obtuvieron los siguientes resultados en seco:
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td>3.85</td>
    <td>3.88</td>
    <td>3.90</td>
    <td>3.62</td>
    <td>3.72</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td>3.80</td>
    <td>3.85</td>
    <td>3.36</td>
    <td>4.01</td>
    <td>3.82</td>
  </tr>
</tbody>
</table>
</pre>
<ol type ="a">
  <li>Construya un intervalo de confianza de $95\%$ para el número medio de gramos de acetanilida que se puede recuperar de $4.85$ gramos de anilina.
  </li>
  <li>Construya un intervalo de confianza de $90\%$ para la proporción de experimentos que recuperan una cantidad de acetanilida superior a $3.82$ gramos, al emplear $4.85$ gramos de anilina.
  </li>
</ol>
17. Dos nuevos medicamentos se dieron a pacientes con hipertensión. El primero de ellos bajó la presión sanguínea de `$16$` pacientes en un promedio de `$11$` puntos, con una desviación estándar de `$6$` puntos; el segundo bajó la presión de otros `$20$` pacientes en un promedio de `$12$` puntos, con desviación estándar de `$8$` puntos. Basado en la información anterior
<ol type ="a">
  <li> Determine un intervalo de confianza de $95\%$ para la diferencia de las reducciones medias en presión sanguínea, suponiendo que las mediciones están distribuidas normalmente.
  </li>
  <li>Calcule la probabilidad de la diferencia de las reducciones medias en la presión sanguínea sean iguales, suponiendo que las mediciones están distribuidas normalmente.
  </li>
</ol>
18. ¿El precio pagado por el atún depende del método de empaque? *Consumer Reports* da el precio promedio estimado para una lata de `$6$` onzas o una bolsa de `$7.06$` onzas de atún, con base en precios pagados a nivel nacional en supermercados. Los precios se registran para una variedad de marcas de atún en la tabla siguiente:
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody><tr>
<td rowspan="1" colspan="2" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold;">Atún Claro 
en Agua</td><td rowspan="1" colspan="2" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold;">Atún Blanco 
en Agua</td>
<td rowspan="1" colspan="2" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold;">Atún Blanco 
en Aceite</td>
<td rowspan="1" colspan="2" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold;">Atún Claro 
en Aceite</td>
</tr><tr>
    <td style="text-align:center;">0.99</td>
    <td style="text-align:center;">0.53</td>
    <td style="text-align:center;">1.27</td>
    <td style="text-align:center;">1.22</td>
    <td style="text-align:center;">1.49</td>
    <td style="text-align:center;">1.29</td>
    <td style="text-align:center;">2.56</td>
    <td style="text-align:center;">0.62</td>
</tr>
<tr>
    <td style="text-align:center;">1.92</td>
    <td style="text-align:center;">1.41</td>
    <td style="text-align:center;">1.19</td>
    <td style="text-align:center;">1.22</td>
    <td style="text-align:center;">1.29</td>
    <td style="text-align:center;">1.00</td>
    <td style="text-align:center;">1.92</td>
    <td style="text-align:center;">0.66</td>
</tr>
<tr>
    <td style="text-align:center;">1.23</td>
    <td style="text-align:center;">1.12</td>
    <td style="text-align:center;">1.18</td>
    <td style="text-align:center;">1.03</td>
    <td style="text-align:center;">1.27</td>
    <td style="text-align:center;">1.27</td>
    <td style="text-align:center;">1.30</td>
    <td style="text-align:center;">0.62</td>
</tr>
<tr>
    <td style="text-align:center;">0.85</td>
    <td style="text-align:center;">0.63</td>
    <td style="text-align:center;">1.28</td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;">1.35</td>
    <td style="text-align:center;">1.28</td>
    <td style="text-align:center;">1.79</td>
    <td style="text-align:center;">0.65</td>
</tr>
<tr>
    <td style="text-align:center;">0.65</td>
    <td style="text-align:center;">0.67</td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;">1.23</td>
    <td style="text-align:center;">0.60</td>
</tr>
<tr>
    <td style="text-align:center;">0.69</td>
    <td style="text-align:center;">0.60</td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;">0.67</td>
    <td style="text-align:center;"></td>
</tr>
<tr>
    <td style="text-align:center;">0.60</td>
    <td style="text-align:center;">0.66</td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
    <td style="text-align:center;"></td>
</tr>
</tbody>
</table>
</pre>
Suponga que las marcas de atún incluidas en el estudio representan una muestra aleatoria de todas las marcas de atún existentes en Estados Unidos, y que estos precios se encuentran normalmente distribuidos. 
<ol type ="a">
  <li> Calcule la probabilidad de que el precio promedio de atún blanco empacado en aceite sea a lo más $1.4$ dolares.
  </li>
  <li> Calcule la probabilidad de que la variabilidad del precio del atún blanco empacado en agua, sea mayor a la variabilidad del precio del atún claro empacado en agua.
  </li>
  <li> Calcule un intervalo de confianza del $92\%$ para el precio promedio de atún claro empacado en aceite. Interprete el intervalo. Específicamente, ¿a qué se refiere el "$95\%$"?
  </li>
  <li> Calcule un intervalo de confianza de $90\%$ para la diferencia en el precio medio de atún claro empacado en agua y atún claro empacado en aceite.
  </li>
</ol>
19. Un experimentador desea comprobar la variabilidad de mediciones obtenidas al usar equipo diseñado para medir el volumen de una fuente de audio. Tres mediciones independientes registradas por este equipo para la misma fuente de sonido fueron `$4.1$`, `$5.2$` y `$10.2$`. Calcule la probabilidad de que la variabilidad del volumen de una fuente de audio sea cuando mucho `$12.53$`. Suponga normalidad.
20. La Environmental Protection Agency (*EPA*) ha establecido un máximo nivel de ruido de `$83_{dB}$` para camiones pesados. La forma en la que se aplique este límite afectará considerablemente al público y a la industria del transporte por carretera. Una forma de aplicar los límites es exigir que todos los camiones se apeguen al límite de ruido. Un segundo método menos satisfactorio es exigir que el nivel medio de ruido de la flota de camiones sea menor al límite. Si se adopta esta última regla, la variación en el nivel de ruido de un camión a otro se hace importante porque una variabilidad grande, implicaría que muchos camiones rebasen ese límite, incluso si el nivel medio de la flota fuera de `$83_{dB}$`. Una muestra aleatoria de seis camiones pesados produjo los siguientes niveles de ruido (en decibeles):
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td>85.4</td>
    <td>86.8</td>
    <td>85.3</td>
    <td>84.8</td>
    <td>86.0</td>
  </tr>
</thead>
</table>
</pre>
Basados en esta información y bajo el supuesto de normalidad
<ol type ="a">
  <li> Calcule la probabilidad de que la varianza de las lecturas de emisión de ruido de camiones, sea mayor a $2_{dB}$. Interprete sus resultados.
  </li>
  <li> Calcule la probabilidad de que la diferencia entre la media real y muestral sea como máximo de $0.4_{dB}$.
  </li>
</ol>
21. En el trabajo de laboratorio es deseable realizar cuidadosas verificaciones de la variabilidad de lecturas producidas en muestras estándar. En un estudio de la cantidad de calcio en agua potable realizado como parte de una evaluación de calidad del agua, la misma muestra estándar se hizo pasar por el laboratorio seis veces en intervalos aleatorios. Las seis lecturas, en partes por millón, fueron 
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td>9.32</td>
    <td>9.48</td>
    <td>9.70</td>
    <td>9.46</td>
    <td>9.26</td>
  </tr>
</thead>
</table>
</pre>
Si asumimos normalidad, cuál es la probabilidad de que la variabilidad de las lectura sea a lo más de `$0.4$` partes por millón.
22. Un instrumento de precisión usado para la medición de la profundidad de una cuenca hidroeléctrica, garantiza dar lecturas que no varían en más de `$2$` unidades. Una muestra de ocho lecturas del instrumento en el mismo punto de la cuenca dio las siguientes mediciones 
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td>353</td>
    <td>358</td>
    <td>351</td>
    <td>363</td>
    <td>375</td>
    <td>365</td>
    <td>369</td>
    <td>348</td>
  </tr>
</thead>
</table>
</pre>
Si asumimos que las mediciones se distribuyen normalmente con una media desconocida pero con una varianza de `$3$`,
<ol type ="a">
  <li> Calcule la probabilidad de que el promedio desconocido de las mediciones realizadas por el instrumento de precisión se encuentre entre $358$ y $363$.
  </li>
  <li> Construya un intervalo de confianza del $84\%$ para la medición promedio de todas las mediciones realizadas por el instrumento de precisión.
  </li>
</ol>
23. El Departamento de zoología de Virginia Tech llevó a cabo un estudio para estimar la diferencia en la cantidad de ortofósforo químico medido en dos estaciones diferentes del río James. El ortofósforo se mide en miligramos por litro. Se reunieron `$15$` muestras de la estación `$1$` y `$12$` muestras de la estación `$2$`. Las `$15$` muestras de la estación `$1$` tuvieron un contenido promedio de ortofósforo de `$3.84$` miligramos por litro y una desviación estándar de `$3.07$` miligramos por litro; en tanto que las `$12$` muestras de la estación `$2$` tuvieron un contenido promedio de `$1.49$` miligramos por litro y una desviación estándar de `$0.80$` miligramos por litro. Calcule un intervalo de confianza de `$95\%e$` para la diferencia en el contenido promedio verdadero de ortofósforo en estas dos estaciones. Suponga que las observaciones provienen de poblaciones normales.
24. Una conjetura de un catedrático del departamento de microbiología, de la Facultad de Odontología de la Universidad de Washington, en St. Louis, Missouri, afirma que un par de tasas diarias de té verde o negro proporciona suficiente flúor para evitar el deterioro de los dientes. ¿Qué tan grande debería ser la muestra para estimar la proporción de habitantes de cierta ciudad que están a favor de tener agua fluorada, si se desea tener al menos un `$99\%$` de confianza en que el estimado está dentro del `$1\%$` del porcentaje verdadero?
25. Un experimento publicado en Popular Science comparó el ahorro de combustible para dos tipos de camiones compactos que funcionan con diesel y están equipados de forma similar. Suponga que se utilizaron `$12$` camiones Volkswagen y `$10$` Toyota en pruebas con una velocidad constante de `$90$` kilómetros por hora. Si los `$12$` camiones Volkswagen promedian `$16$` kilómetros por litro con una desviación estándar de `$1.0$` kilómetros por litro, y los `$10$` Toyota promedian `$11$` kilómetros por litro con una desviación estándar de `$0.8$` kilómetros por litro, construya un intervalo de confianza del `$90\%$` para la diferencia entre los kilómetros promedio por litro de estos dos camiones compactos. Suponga que las distancias por litro para cada modelo de camión están distribuidas de forma aproximadamente normal.
26. Una empresa de taxis trata de decidir si comprará neumáticos de la marca `$A$` o de la marca `$B$` para su flotilla de taxis. Para estimar la diferencia entre las dos marcas realiza un experimento utilizando `$12$` neumáticos de cada marca, los cuales utiliza hasta que se desgastan. Los resultados son, 
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Marca A</td>
    <td style="font-weight: bold">Marca B</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>36300</td>
    <td>38100</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>5000</td>
    <td>6100</td>
  </tr>
</tbody>
</table>
</pre>
Calcule un intervalo de confianza del `$95\%$` para la diferencia entre los promedios de las dos marcas de neumáticos, suponiendo que las poblaciones se distribuyen de forma aproximadamente normal.
27. Los anunciantes en televisión pueden creer erróneamente que casi todas las personas que ven Televisión entienden la mayor parte de los anuncios que ven y escuchan. Un estudio de investigación reciente pidió a `$2300$` personas de más de `$13$` años de edad que vieran extractos de publicidad de televisión de `$30$` segundos de duración. De éstos, `$1914$` televidentes entendieron mal todo o parte del extracto que vieron. Encuentre un intervalo de confianza de `$95\%$` para la proporción de todos los teleespectadores (de los cuales la muestra es representativa) que entenderán mal el total o parte de los extractos de televisión empleados en este estudio.
28. Se considera usar dos marcas diferentes de pintura vinílica, y para ello, se decide seleccionar `$15$` especímenes de cada tipo de pintura, y se realizó la medición de los tiempos de secado en horas, obteniendo los siguientes resultados:
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody><tr>
<td rowspan="1" colspan="5" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold; border-right-width: thick;">Pintura A</td><td rowspan="1" colspan="5" style="text-align:center;vertical-align: middle;width: 4.5rem;font-weight: bold;">Pintura B</td>
</tr><tr>
    <td style="text-align:center;">3.5</td>
    <td style="text-align:center;">2.7</td>
    <td style="text-align:center;">3.9</td>
    <td style="text-align:center;">4.2</td>
    <td style="text-align:center; border-right-width: thick;">3.6</td>
    <td style="text-align:center;">4.7</td>
    <td style="text-align:center;">3.9</td>
    <td style="text-align:center;">4.5</td>
    <td style="text-align:center;">5.5</td>
    <td style="text-align:center;">4.0</td>
</tr>
<tr>
    <td style="text-align:center;">2.7</td>
    <td style="text-align:center;">3.3</td>
    <td style="text-align:center;">5.2</td>
    <td style="text-align:center;">4.2</td>
    <td style="text-align:center; border-right-width: thick;">2.9</td>
    <td style="text-align:center;">5.3</td>
    <td style="text-align:center;">4.3</td>
    <td style="text-align:center;">6.0</td>
    <td style="text-align:center;">5.2</td>
    <td style="text-align:center;">3.7</td>
</tr>
<tr>
    <td style="text-align:center;">4.4</td>
    <td style="text-align:center;">5.2</td>
    <td style="text-align:center;">4.0</td>
    <td style="text-align:center;">4.1</td>
    <td style="text-align:center; border-right-width: thick;">3.4</td>
    <td style="text-align:center;">5.5</td>
    <td style="text-align:center;">6.2</td>
    <td style="text-align:center;">5.1</td>
    <td style="text-align:center;">5.4</td>
    <td style="text-align:center;">4.8</td>
</tr>
</tbody>
</table>
</pre>
Si se supone que los tiempos de secado se distribuye normalmente. Calcule un intervalo de confianza del `$95\%$` para la diferencia promedio entre los tiempos medios de secado de la Pintura B y la Pintura A.
29. A dos grupos de ratas diabéticas se les suministran dos niveles de dosis de insulina (alto y bajo) para verificar la capacidad de fijación de esta hormona. Se obtuvieron los siguientes datos.
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Dosis baja</td>
    <td style="font-weight: bold">Dosis alta</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Tamaño muestra</td>
    <td>8</td>
    <td>13</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>1.98</td>
    <td>1.30</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>0.51</td>
    <td>0.35</td>
  </tr>
</tbody>
</table>
</pre>
Determine un intervalo de confianza del `$95\%$` para la diferencia en la capacidad promedio verdadera de fijación de la insulina entre las dos muestras.
30. Un fabricante de baterías para automóvil afirma que sus baterías durarán, en promedio, `$3$` años con una varianza de `$1$` año. Suponga que se toma una muestra aleatoria de `$15$` de estas baterías y se les mide su tiempo de duración, en años, obteniendo los siguientes reusltados
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td>1.9</td>
    <td>2.4</td>
    <td>3.0</td>
    <td>3.5</td>
    <td>4.2</td>
    <td>3.6</td>
    <td>2.7</td>
    <td>1.5</td>
    <td>3.5</td>
    <td>2.7</td>
    <td>2.9</td>
    <td>3.1</td>
    <td>3.7</td>
    <td>1.9</td>
    <td>4.4</td>
  </tr>
</thead>
</table>
</pre>
Suponiendo que la duración de todas las baterías se distribuye de forma aproximadamente normal.
<ol type ="a">
  <li> Calcule la probabilidad de que el tiempo promedio de durabilidad de todas las baterías sea de $3$ o más años.
  </li>
  <li> Construya un intervalo de confianza del $92\%$ para el promedio de durabilidad de todas las baterías y después decida si la afirmación del fabricante sobre que el promedio de durabilidad es de $3$, es o no válida.
  </li>
</ol>
