---
layout: post
title: "Clase 06"
main-class: 'clase'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: |
  Introducción a variables aleatorias. <br/>
  Funciones de probabilidad discretas. <br/>
  Función de distribución acumulada. <br/>
  Esperanza matemática y varianza.
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all")})
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Clase06"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```


## Variables aleatorias
Es una función que asocia un número real a cada elemento del espacio muestral `$S$`. Comúnmente las variables aleatorias se denotan por letras mayúsculas del final del alfabeto `$(X,Y,Z)$` y a los valores observados por letras minúsculas `$(x,y,z)$`.

Las variables aleatorias se pueden clasificar en tres tipos

* **Variables Bernoulli:** Cualquier variable aleatoria cuyos posibles valores sean 0 o 1.
* **Variables discretas:** Son aquellas que tienen un número finito de posibilidades o una serie interminable de elementos como números enteros existentes (es enumerable).
* **Variables continuas:** Son aquellas que contienen un número infinito de posibilidades, o igual número de puntos que un segmento de recta.

## Funciones de probabilidad discreta

Se dice que el conjunto de pares ordenados `$(x,p(x))$` es una función de masa de probabilidad (*fmp*) de la variable aleatoria discreta `$X$`, si para cualquier resultado posible de `$X$` se cumple que

1. `$p(x)\geq0$` para todo `$x \in$` al rango de `$X$`
2. `$\sum_x p(x)=1$`
3. `$p(x)=\mathbb P(X=x)$`

## Función de distribución acumulada caso discreto

La función de distribución acumulada (*fda*) denotada por `$F(x)$`, para una variable aleatoria discreta `$X$` con distribución de probabilidad `$p(x)$` es de la forma 
`\begin{align*}
F(x)=P(X\leq x)=\sum_{t\leq x}p(t) \quad \quad -\infty<x<\infty
\end{align*}`

para cualquier `$x$` dentro del rango de `$X$`, `$F(x)$` será la suma acumulada de todos los valores de rango de `$X$` menores a `$x$`.

## Esperanza matemática caso discreto

Si `$x$` es una variable aleatoria con *fmp* `$p(x)$`, entonces la media o valor esperado de la variable aleatoria se denota por `$\mathbb{E}(X)$` o `$\mu$` está dada por
`\begin{align*}
\mathbb{E}(X)=\sum_{x}xp(x)
\end{align*}`

### Propiedades de la esperanza matemática
Sea `$a$` y `$b$` dos números constantes (reales) y `$X$` una variable aleatoria, entonces se tiene que

* `$\mathbb{E}(a)$`
* `$\mathbb{E}(aX+b)=a\mathbb{E}(X)+b$`
* si `$g(X)$` es una función de `$X$`, entonces

`\begin{align*}
\mathbb{E}(g(X))=\sum_xg(x)p(x)
\end{align*}`

## Varianza caso discreto
Sea `$X$` una variable aleatoria con *fmp* `$p(x)$`, entonces si `$m(X) = (X - \mathbb{E}(X))^2$`, se tendrá que la varianza de `$X$` que se denota `$Var(X)$` o `$\sigma^2$` estará dada por
`\begin{align*}
Var(X) = \mathbb{E}\left[\left(X-\mathbb{E}(X)\right)^2\right]=\sum_x(x-\mathbb{E}(X))^2p(x)
\end{align*}`

Puede demostrarse a partir de la ecuación anterior, que una alternativa para el cálculo de la `$Var(X)$` es de la forma

`\begin{align*}
Var(X) = \mathbb{E}(X^2) - \mathbb{E}(X)^2
\end{align*}`

además, la raíz cuadrada de la varianza de `$X$` se llama desviación estándar de `$X$`, se denota por `$Sd(X)$` o `$\sigma$` y se define como
`\begin{align*}
Sd(X) = \sqrt{Var(X)}
\end{align*}`
