---
layout: post
title: "Parcial I"
main-class: 'presentaciones'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Parcial I
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Parcial I"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 8:30 am, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
Recuerden interpretar todos los resultados!!! TODOS!!!! TOOOOOODDDDOOOOOOSSSS!!!!!! en el contexto del enunciado.

* [Aguirre Monsalve Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1020495555.pdf){:target="_blank"}
* [Alvarez Jaramillo Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1001420406.pdf){:target="_blank"}
* [Álvarez Muñeton Jorge Neliecer](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1035233013.pdf){:target="_blank"}
* [Arroyave Murillo Juan Diego](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1007368680.pdf){:target="_blank"}
* [Ascanio Estrada Andres Leonardo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1065894729.pdf){:target="_blank"}
* [Avendaño Salazar Brahian Estiven](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1152467235.pdf){:target="_blank"}
* [Caballero Castañeda Sebastian Eduardo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1010010607.pdf){:target="_blank"}
* [Camelo Carrillo Christiam Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1007665627.pdf){:target="_blank"}
* [Cuaical Tapie William Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1007292685.pdf){:target="_blank"}
* [Escobar Londoño Juan Pablo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1000920301.pdf){:target="_blank"}
* [Escorcia Pajaro Valery Estefy](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1002244380.pdf){:target="_blank"}
* [Florez Gallego Maria Paulina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1000549222.pdf){:target="_blank"}
* [Henao Otalvaro Natalia Marcela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P43463025.pdf){:target="_blank"}
* [Herrera Giraldo Laura](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1001017464.pdf){:target="_blank"}
* [Hincapie Gomez Leidy Tatiana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1010122767.pdf){:target="_blank"}
* [Longas Rivas Jhon Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1193326786.pdf){:target="_blank"}
* [Martinez Gutierrez Cesar Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1063082773.pdf){:target="_blank"}
* [Mosquera Franco Arthur Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1003073445.pdf){:target="_blank"}
* [Niño Valderrama Nicolás](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1017241764.pdf){:target="_blank"}
* [Noreña Cadavid Susana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1000748392.pdf){:target="_blank"}
* [Pantoja Quiscualtud Alexandra Carolina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1087425594.pdf){:target="_blank"}
* [Perez Castilla Karen Marcela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1005605305.pdf){:target="_blank"}
* [Polo Pineda Daniela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1000085308.pdf){:target="_blank"}
* [Puerta Campo Rosa Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1002389631.pdf){:target="_blank"}
* [Puerta Dussan Stefania](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1007286384.pdf){:target="_blank"}
* [Ramirez Lopez Santiago](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1037669252.pdf){:target="_blank"}
* [Reyes Anaya Karol Melissa](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1098757410.pdf){:target="_blank"}
* [Rico Mejia Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1037654941.pdf){:target="_blank"}
* [Vargas Cely Andrea Juliana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1010149009.pdf){:target="_blank"}
* [Vasquez Ortiz Carlos Enrique](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1003004985.pdf){:target="_blank"}
* [Velasquez Cañas Maria Alejandra](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1000567192.pdf){:target="_blank"}
* [Velez Osorno Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1037667652.pdf){:target="_blank"}
* [Zarate Miranda Gabriela Andrea](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/ParcialI/P1017274210.pdf){:target="_blank"}


<h1> Mucha Suerte! </h1>



