---
layout: post
title: "Trabajo II"
main-class: 'presentaciones'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Trabajo II
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Trabajo II"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

# Trabajo
El Trabajo deberá solucionarse a mano, y enviar los resultado (Word, escaner o foto a la hoja resuelta) a más tardar el día sábado 8 de junio a las 11:59 PM, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
**Lea atentamente el Trabajo**. Recuerden interpretar todos los resultados en el contexto del enunciado!!! y aplicar los filtros diferentes en cada punto!!!!, **no hacerlo les va hacer perder punto!!!!** >:c

# Nota 2
**Si resuelve el trabajo en parejas**, recuerde que debe juntar las dos bases de datos como se explicó hoy en clase, mediante la función rbind(). Dado que los enunciados son diferentes para cada persona, simplemente cogen uno de los dos enunciados y trabajan sobre ese, y cuando me envíen el trabajo hacen la aclaración sobre cuál trabajaron :D

# Bases y enunciados
## Cortes Sanchez Sebastian
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1222454358.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1222454358.xlsx){:target="_blank"}

## Cortina Prieto Valeria
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1007987474.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1007987474.xlsx){:target="_blank"}

## Galvis Carballo Angela Camila
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1025641130.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1025641130.xlsx){:target="_blank"}

## Hincapié López Daniel Felipe
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001095936.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1001095936.xlsx){:target="_blank"}

## Meza Causado Elias
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017230790.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1017230790.xlsx){:target="_blank"}

## Morato Merchan Cristian Camilo
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000005584.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1000005584.xlsx){:target="_blank"}

## Quintero Pineda Carolina
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1038404303.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1038404303.xlsx){:target="_blank"}

## Rosas Mendoza Daniel
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1036339232.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1036339232.xlsx){:target="_blank"}

## Tejada Vasquez Angie Saray
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000195100.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1000195100.xlsx){:target="_blank"}

## Torres Castaneda Laura
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017262338
.pdf){:target="_blank"}
* [Base de Datos](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/B1017262338.xlsx){:target="_blank"}

<h1> Mucha Suerte! </h1>

