---
layout: post
title: "Parcial II"
main-class: 'presentaciones'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Parcial II
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Parcial II"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 8:30 am, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
Recuerden interpretar todos los resultados en el contexto del enunciado!!!

* [Alvarez Jaramillo Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001420406.pdf){:target="_blank"}
* [Ascanio Estrada Andres Leonardo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1065894729.pdf){:target="_blank"}
* [Atehortua Bedoya Natalia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000439514.pdf){:target="_blank"}
* [Bravo Carpio Evelio](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1143393216.pdf){:target="_blank"}
* [Camelo Carrillo Christiam Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007665627.pdf){:target="_blank"}
* [Ceballos Alvarez Miguel Angel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001226139.pdf){:target="_blank"}
* [Duque Daza Andres Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152706282.pdf){:target="_blank"}
* [Garrido Rodriguez Peter Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1085952515.pdf){:target="_blank"}
* [Gonzalez Gonzalez Valeria](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000099730.pdf){:target="_blank"}
* [Longas Rivas Jhon Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1193326786.pdf){:target="_blank"}
* [López Serna Kateryn](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1020453931.pdf){:target="_blank"}
* [Martinez Gutierrez Cesar Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1063082773.pdf){:target="_blank"}
* [Mosquera Franco Arthur Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1003073445.pdf){:target="_blank"}
* [Rico Mejia Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037654941.pdf){:target="_blank"}
* [Rios Cañas Dahiana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001639373.pdf){:target="_blank"}
* [Rios Muñoz Emanuel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017276598.pdf){:target="_blank"}
* [Rojas Pérez Miguel Ángel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000748322.pdf){:target="_blank"}
* [Simmonds Jaimes Gabriela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1002579812.pdf){:target="_blank"}
* [Toro Lopez Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001469363.pdf){:target="_blank"}
* [Yepes Serna Cristian Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007417936.pdf){:target="_blank"}

<h1> Mucha Suerte! </h1>



