---
layout: post
title: "Parcial IV"
main-class: 'practica'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Parcial IV
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Parcial IV"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

# Parcial
El parcial deberá solucionarse a mano, y enviar los resultado (escanear o tomar foto a la hoja resuelta) a más tardar a las 8:30 am, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>. 

# Nota
Recuerden plantear y probar la hipótesis de normalidad y la hipótesis para diferencia de varianzas en caso de ser necesario en el punto. Además, recuerden interpretar todos los resultados!!! TODOS!!!! TODOS!!!!!!!! en el contexto del enunciado.

# PosData
Reciclé el enunciado del Quiz III y IV para que el parcial les pareciera más familiar :v ¡Mucha Suerte en ese final!

* [Arcila Galvis Faber Esteban](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/Q1017276234.pdf){:target="_blank"}
* [Barrientos Cortés Susana Eugenia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1152687823.pdf){:target="_blank"}
* [Bedoya Carvajal Jhon Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1028037122.pdf){:target="_blank"}
* [Buitrago Yepez Julio César](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P98534085.pdf){:target="_blank"}
* [Giraldo Valencia Yuddy Lorena](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1041328895.pdf){:target="_blank"}
* [Gomez Giraldo Valentina](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1001250142.pdf){:target="_blank"}
* [Martinez Ayala Juan Esteban](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1007900969.pdf){:target="_blank"}
* [Mosquera Franco Arthur Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1003073445.pdf){:target="_blank"}
* [Muñoz Blandon Juan Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1000895681.pdf){:target="_blank"}
* [Peñaloza Villegas Edwin Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037655076.pdf){:target="_blank"}
* [Tangarife González Sebastian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1037665594.pdf){:target="_blank"}
* [Vallejo Quiroz Jose Alfredo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1017239918.pdf){:target="_blank"}
* [Villota Moreno Fernando Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Parcial/P1085347829.pdf){:target="_blank"}

<h1> Mucha Suerte! </h1>



