---
layout: post
title: "Práctica 05"
main-class: 'practica'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: |
  Ejercicio sobre: <br>
  - Errores tipo I y tipo II <br>
  - Pruebas de hipótesis <br>
  - Pruebas de bondad de ajuste
              
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Práctica05"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

## Lista de ejercicios

1. Se realiza un estudio para determinar si los habitantes de dos islas ubicadas en el Pacífico poseen o no la misma ascendencia racial, y para ello un antropólogo decide emplear los índices cefálicos de `$12$` hombres adultos de la isla `$A$` y `$18$` de la isla `$B$` obteniendo los sigiuentes resultados
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td colspan="10" style="text-align:center;font-weight: bold">Isla A</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td>78.96</td>
    <td>79.30</td>
    <td>78.79</td>
    <td>75.59</td>
    <td>74.52</td>
    <td>75.97</td>
    <td>74.69</td>
    <td>73.31</td>
    <td>76.78</td>
    <td>80.86</td>
  </tr>
  <tr>
    <td>81.09</td>
    <td>76.94</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>
</pre>
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td colspan="10" style="text-align:center;font-weight: bold">Isla B</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td>72.27</td>
    <td>71.40</td>
    <td>74.25</td>
    <td>73.55</td>
    <td>73.87</td>
    <td>71.17</td>
    <td>73.38</td>
    <td>72.39</td>
    <td>72.09</td>
    <td>73.81</td>
  </tr>
  <tr>
    <td>68.23</td>
    <td>71.57</td>
    <td>72.89</td>
    <td>74.89</td>
    <td>73.46</td>
    <td>76.79</td>
    <td>70.98</td>
    <td>69.58</td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>
</pre>
Mediante el empleo de un nivel de significancia del `$8\%$` pruebe si es razonable suponer que las dos poblaciones poseen en promedio índices cefálicos similares.
2. Se realiza un estudio en un río para observar la concentración de zinc que éste posee, y para ello se reaiza una muestra aleatoria de `$36$` sitios diferentes y se encuentra que la concentración promedio de zinc es de `$2.8$` gramos po mililitro con una desviación estándar de `$0.6$` gramos por mililitro. Si la función de probabilidad no es conocida, pero se sabe su desviación estándar es de `$0.3$` gramos por mililitro, pruebe con un nivel de confianza del `$5\%$` si la concentración media de zinc es de al menos `$3$` gramos por mililitro.
3. Un botánico desea probar la hipótesis de que el diámetro promedio de las flores de una planta en particular es `$9.6_{cm}$`, y para probar ésto, decide tomar una muestra aleatoria de `$80$` flores y no rechazar la hipótesis si la media de la muestra cae entre `$9.3_{cm}$` y `$9.9_{cm}$`; si la media de esta muestra cae fuera de este intervalo, el botánico rechazará tal hipótesis. ¿Qué decisión deberá tomará el botánico y qué situación estará ocurriendo si
<ol type ="a">
  <li> obtiene una media muestral de $10.2_{cm}$ y la verdadera media $\mu=9.6_{cm}$
  </li>
  <li> obtiene una media muestral de $10.2_{cm}$ y la verdadera media $\mu=9.8cm$
  </li>
  <li> obtiene una media muestral de $9.2_{cm}$ y la verdadera media $\mu=9.6cm$
  </li>
  <li> obtiene una media muestral de $9.2_{cm}$ y la verdadera media $\mu=9.8cm$
  </li> 
  <li>Calcule la probabilidad de cometer Error Tipo I.
  </li>
  <li>Calcule la probabilidad de cometer Error Tipo II, si la verdadera media $\mu=9.8cm$.
  </li>
</ol>
4. Suponga que el contenido de ácido sulfúrico, en litros, de una muestra aleatoria de `$7$` contenedores similares es de 
`\begin{align*}
9.8 \quad 10.2 \quad 10.4 \quad 9.8 \quad 10.0 \quad 10.2 \quad 9.6
\end{align*}`
Emplee el P-valor para verificar si hay evidencia sobre que el contenido promedio de todos los contenedores de ácido sulfúrico es de más de `$10$` litros.
5. Para un experimento de pruebas psicológicas se seleccionan al azar `$25$` sujetos de prueba y se les mide sus tiempos de reacción, en segundos, ante un estímulo particular, obteniendo que el tiempo promedio de reacción de los sujetos es de `$6.2$` segundos con una desviación estándar de `$1.3$` segundos. La experiencia sugiere que la varianza en los tiempos de reacción ante los diferentes tipos de estímulos es de `$4_{s^2}$` y que la distribución de probabilidad para los tiempos de reacción es aproximadamente normal. Basado en lo anterior, emplee un nivel de significancia del `$98\%$` para probar si el tiempo medio de reacción de todos los individuos es como máximo de `$5.5$` segundos.
6. El gerente de una gran tabacalera afirma en una conferencia de prensa que el contenido promedio de alquitrán de los cigarrillos que produce es de `$14$` mg/cigarrillo. Un ingeniero realiza `$5$` mediciones del contenido de alquitrán de cierta clase de cigarrillos para observar si la afirmación del gerente sobre el contenido de alquitrán es cierta, y obtiene en la muestra los siguientes resultados
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
    <td>14.5</td>
    <td>14.2</td>
    <td>14.4</td>
    <td>14.3</td>
    <td>14.6</td>
  </tr>
</tbody>
</table>
</pre>
¿Encuentra apoyo la afirmación del gerente de la tabacalera?, emplee un nivel de significancia del `$5\%$` para su conclusión.
7. Suponga que el grupo ALIADO, realiza un estudio sobre la altura que poseen los estudiantes de la Universidad, y para ello, toma una muestra aleatoria de `$28$` estudiantes universitarios y encuentra que la estatura promedio fue de `$174.5$` centímetros con una desviación estándar de `$6.9$` centímetros. Empleando un nivel de significancia del `$2\%$`, pruebe si la altura promedio de todos los estudiantes de la universidad es de al menos `$173$` centímetros.
8. El gerente de una planta sospecha que el número promedio de piezas que produce un trabajador en particular por día, es menor que el número promedio de piezas de los demás trabajadores. Por ello, el gerente decide observar el número de piezas que produce este trabajador durante diez días, seleccionados al azar, obteniendo los siguientes resultados
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
    <td>15</td>
    <td>12</td>
    <td>28</td>
    <td>13</td>
    <td>12</td>
    <td>15</td>
    <td>16</td>
    <td>9</td>
    <td>8</td>
    <td>14</td>
  </tr>
</tbody>
</table>
</pre>
<ol type ="a">
  <li> Si se sabe que la desviación estándar para todos los trabajadores es de `$2$` unidades, emplee un nivel de significancia del $2\%$ para probar si tiene o no apoyo la sospecha del gerente de que el número promedio de unidades producidas por el trabajador es menor a $15$ unidades? Obtener el P-valor para el contraste.
  </li>
  <li> Emplee un nivel de significancia del $5\%$ para probar si la proporción de días que el trabajador produce menos de $15$ unidades es mayor al $80\%$.
  </li>
</ol>
9. ¿Está menguando el romance de los estadounidenses con el cine?, En una encuesta realizada por la empresa Gallup a `$800$` adultos seleccionados de forma aleatoria, se encontró que `$45\%$` de los encuestados indicaron que el cine estaba mejorando, mientras que, `$43\%$` de los encuestados dijeron que el cine estaba empeorando. Basados en lo anterior, emplee un nivel de significancia del `$12\%$` para probar si la proporción total de adultos que piensan que el cine está mejorando es superior al `$50\%$`.
10. Un estudio del número de comidas de negocios que los ejecutivos de las industrias de seguros y bancos reclaman mensualmente como gastos deducibles, se basó en muestras aleatorias y produjo los siguientes resultados
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Seguros</td>
    <td style="font-weight: bold">Bancos</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Muestra</td>
    <td>40</td>
    <td>50</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>9.1</td>
    <td>8.0</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>1.9</td>
    <td>2.1</td>
  </tr>
</tbody>
</table>
</pre>
Use un nivel del `$5\%$` de significancia para probar si el gasto promedio deducible de ambas poblaciones es igual. Encuentre el P-valor para esta prueba.
11. A la mayoría de estadounidenses les gusta participar en eventos deportivos o al menos verlos. Algunos sienten que los deportes tienen más que sólo valor de entretenimiento, tanto así, que en una encuesta realizada a `$1000$` adultos, realizada por KRC Research \& Consulting, se encontró que `$68\%$` sintieron que los deportes de gran atractivo tienen un efecto positivo en la sociedad. Emplee un nivel de significancia del `$5\%$` para probar si la mayoría de estadounidenses piensan que los deportes tienen un efecto positivo en la sociedad.
12. Para una comparación de los porcentajes de piezas defectuosas producidas por dos líneas de montaje, de cada línea se seleccionaron muestras aleatorias independientes de `$100$` piezas. La línea `$A$` produjo `$18$` piezas defectuosas en la muestra y la línea `$B$` contenía `$12$` piezas defectuosas. Emplee un nivel de significancia del `$2\%$` para probar si una línea de montaje produce una proporción más alta de piezas defectuosas que la otra.
13. Se tiene la creencia que las profesoras de la Universidad suelen gastar en promedio más dinero en café que los profesores en un mes. Para probar ésto, se realiza un estudio en el cual se toma una muestra aleatoria de profesoras y profesores y se registra el gasto que tuvieron durante el mes, obteniendo los siguientes resultados, en miles de pesos
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Profesores</td>
    <td style="font-weight: bold">Profesoras</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Muestra</td>
    <td>20</td>
    <td>28</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>33</td>
    <td>38.5</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>2.9</td>
    <td>3.1</td>
  </tr>
</tbody>
</table>
</pre>
Use un nivel del `$5\%$` de significancia para probar la hipótesis planteada. Emplee el P-valor en sus conclusión.
14. Suponga que nos encontramos en época de elecciones, y que el responsable de la campaña política del candidato `$A$` piensa en el ambiente de las últimas semanas previas a las elecciones. Él piensa que su candidato se encuentra en igual posición que su oponente, el candidato `$B$`, pero han ocurrido algunos reveses en forma reciente. El responsable lleva a cabo una encuesta de percepción electoral a `$1500$` ciudadanos. Si de los `$1500$`, `$737$` indican una preferencia por el candidato `$A$`, ¿existe alguna razón para creer que el candidato `$A$` se encuentra en desventaja con relación al candidato `$B$`?, Use un nivel de significancia del `$5\%$`.
15. Una bióloga quiere probar la hipótesis de que la envergadura media de cierta clase de insectos es `$12.3_{mm}$` contra la alternativa de que no es de `$12.3_{mm}$`. Si toma una muestra aleatoria de `$12$` insectos y decide aceptar la hipótesis nula si y sólo si la media de la muestral cae entre `$12.0_{mm}$` y `$12.6_{mm}$`, 
<ol type ="a">
  <li> Calcule la probabilidad de cometer un error tipo I.
  </li>
  <li> Calcule la probabilidad de cometer un error tipo II, si la media real de la envergadura de los insectos es de $12.5_{mm}$
  </li>
  <li>¿Qué decisión estaría tomando la bióloga si obtiene de la muestra un media de $12.9_{mm}$, y se tiene que la media real de la envergadura de los insectos es $12.5mm$?
  </li>
  <li>¿Qué decisión estaría tomando la bióloga si obtiene de la muestra un media de $12.9_{mm}$, y se tiene que la media real de la envergadura de los insectos es $12.3_{mm}$?
  </li>
</ol>
16. Las calificaciones del Examen de Evaluación Escolar (SAT por sus siglas en inglés), que han bajado lentamente desde el inicio del examen, ahora han empezado a subir. Originalmente, una calificación de `$500$` estaba considerada como promedio. Las calificaciones medias para el `$2005$` fueron aproximadamente `$520$` para el examen verbal y `$508$` para el examen de matemáticas. Una muestra aleatoria de las calificaciones del examen, de `$20$` alumnos de último año de una preparatoria urbana de gran tamaño, produjo las medias y desviaciones estándar citadas en la tabla siguiente
<pre style="font-family: 'Open Sans',sans-serif; margin-bottom: -4rem; margin-top: -2rem; font-size: 98%;">
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
  <tr>
    <td></td>
    <td style="font-weight: bold">Verbal</td>
    <td style="font-weight: bold">Matemáticas</td>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="font-weight: bold">Media muestral</td>
    <td>505</td>
    <td>495</td>
  </tr>
  <tr>
    <td style="font-weight: bold">Desviación estándar muestral</td>
    <td>57</td>
    <td>69</td>
  </tr>
</tbody>
</table>
</pre>
<ol type ="a">
  <li> Suponiendo normalidad, emplee un nivel de significancia del $10\%$ para observar si la calificación promedio del SAT verbal obtenida por los alumnos de último año es superior a $520$ puntos.
  </li>
   <li> Suponiendo normalidad, emplee un nivel de significancia del $10\%$ para observar si la calificación promedio del SAT de matemáticas obtenida por los alumnos de último año es a lo más de $508$ puntos.
  </li>
  <li> Suponiendo normalidad, emplee un nivel de significancia del $10\%$ para observar si la variabilidad en la calificación obtenida por los estudiantes en el SAT verbal y el SAT de matemáticas es la misma.
  </li>
</ol>
