---
layout: post
title: "Trabajo Inferencia"
main-class: 'presentaciones'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: Trabajo Inferencia

header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Trabajo"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)
```

# Trabajo Inferencia
El trabajo deberá solucionarse y enviar los resultado con los análisis correspondientes a más tardar el día Miércoles 22 de Septiembre a las 11:59 PM, al correo electrónico <a target="_blank" href="mailto:jivan.perez@udea.edu.co"> jivan.perez@udea.edu.co</a>.

Recuerden que si van a hacer el trabajo en parejas, deben unir las dos bases de datos, ya sea en R o sea en Excel.

Quedo atento a cualquier duda o inquietud que les surja durante el trabajo. No duden en escribirme.

## Enunciado trabajo 
* [Enunciado](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/TrabajoInferencia.pdf){:target="_blank"}

## Bases de datos 

* [Alvarez Jaramillo Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001420406.xlsx){:target="_blank"}
* [Ascanio Estrada Andres Leonardo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1065894729.xlsx){:target="_blank"}
* [Atehortua Bedoya Natalia](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000439514.xlsx){:target="_blank"}
* [Bravo Carpio Evelio](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1143393216.xlsx){:target="_blank"}
* [Camelo Carrillo Christiam Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1007665627.xlsx){:target="_blank"}
* [Ceballos Alvarez Miguel Angel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001226139.xlsx){:target="_blank"}
* [Duque Daza Andres Felipe](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1152706282.xlsx){:target="_blank"}
* [Garrido Rodriguez Peter Daniel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1085952515.xlsx){:target="_blank"}
* [Gonzalez Gonzalez Valeria](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000099730.xlsx){:target="_blank"}
* [Longas Rivas Jhon Alexánder](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1193326786.xlsx){:target="_blank"}
* [López Serna Kateryn](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1020453931.xlsx){:target="_blank"}
* [Martinez Gutierrez Cesar Andres](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1063082773.xlsx){:target="_blank"}
* [Mosquera Franco Arthur Jose](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1003073445.xlsx){:target="_blank"}
* [Rico Mejia Cristian](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1037654941.xlsx){:target="_blank"}
* [Rios Cañas Dahiana](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001639373.xlsx){:target="_blank"}
* [Rios Muñoz Emanuel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1017276598.xlsx){:target="_blank"}
* [Rojas Pérez Miguel Ángel](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1000748322.xlsx){:target="_blank"}
* [Simmonds Jaimes Gabriela](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1002579812.xlsx){:target="_blank"}
* [Toro Lopez Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1001469363.xlsx){:target="_blank"}
* [Yepes Serna Cristian Mateo](https://github.com/jiperezga/jiperezga.github.io/raw/master/Dataset/Trabajo/T1007417936.xlsx){:target="_blank"}

<h1> Mucha Suerte! </h1>