---
layout: post
title: "Clase 16"
main-class: 'clase'
permalink: /MuestreoySeriesdeTiempo/MyST:title.html
tags:

introduction: |
  Métodos de muestreo probabilístico: </br>
  - Muestreo aleatorio estratificado </br>
  - Estimación de parámetros de la población </br>
  - Estimación de la media poblacional </br>
  - Intervalos de confianza para la media poblacional </br>
  - Intervalos de confianza para el total poblacional </br>
  - Intervalos de confianza para la proporción poblacional
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../MuestreoySeriesdeTiempo/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
link-citations: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../MuestreoySeriesdeTiempo/images/", "Clase16"),
               cache.path = "../../MuestreoySeriesdeTiempo/cache/",
               cache = FALSE)
```

## Métodos de muestreo
### Muestreo aleatorio estratificado (MAE)
Es una técnica de muestreo mediante la cual se obtiene una
muestra a partir la segmentación o separación de los elementos de una población en grupos mutuamente excluyentes, denotados como estratos. Posteriormente, a partir de la segmentación realizada, se realiza el muestreo de cada estrato, mediante la técnica de MAS, independiente.

Para emplear este método se requiere que la población objetivo, tenga un comportamiento **homogeneo** dentro de cada uno de los `$L$` estratol, y un comportamiento **heterogeneo** entre estratos, con respecto a las características de interés.

El objetivo del método de MAE, será maximizar la información obtenida o minimizar el valor del límite del error de estimación `$B$`, para cada una de los estratos, teniendo en
cuenta la variabilidad de la población cuando ésta debido a que ésta no posee un comportamiento **homogeneo**, además de obtener estimaciones
de los parámetros poblacionales de interés para cada uno de los
estratos individualmente.

En la práctica, cuando se emplea este tipo de muestreo, **se debe especificar claramente cada uno de los estratos**, así como el estrato en la cual se ubica cada unidad muestral. Adicionalmente, se debe seleccionar **la muestra de cada estrato de forma independiente**, mediante un MAS Finalmente, se debe asegurar la independencia en la selección de MAS de cada uno de los estratos.

### Estimación de parámetros de la población

#### Estimación del total de la población `$\tau$`
Sea `$\tau_i$` el total asociado al i-ésimo estrato, con `$i = 1,2,\ldots, L$`, con `$L$` el número de estratos. Entonces, se tendrá que el total poblacional `$\tau$` estará dado por
`\begin{align*}
\tau = \sum_{i=1}^L \tau_i
\end{align*}`

Tanto `$\tau$` como `$\tau_i$` son valores generalmente desconocidos, lo cual hace que se requieran estimadores para cada uno de ellos. El estimador para el total del i-ésimo estrato `$\tau_i$` estará dado por la expresión
`\begin{align*}
\hat{\tau} = N_i \bar{Y}_i
\end{align*}`

para `$i = 1,2, \ldots, L$`. Como se observa, este estimador está dado por el total de individuos pertenecientes al i-ésimo estrato `$N_i$`, y el estimador `$\bar{Y}_i$` del promedio poblacional del i-ésimo estrato `$\mu_i$`.

Dado lo anterior, se tendrá que un estimador puntual para el parámetro del total de toda la población bajo estudio `$\tau$` será 
`\begin{align*}
\hat{\tau}_{t} = \sum_{i=1}^L \hat{\tau}_i = \sum_{i=1}^L N_i \bar{Y}_i
\end{align*}`

Ahora, dado que el MAE requiere que haya independencia entre los MAS de los estratos, se tendrá que la varianza del estimador `$\hat{\tau}$` será de la forma
`\begin{align*}
Var(\hat{\tau}) & = Var\left(\sum_{i=1}^L \hat{\tau}_i \right) \\
                & = \sum_{i=1}^L Var(N_i \bar{Y}_i) \\
                & = \sum_{i=1}^L N_i^2Var(\bar{Y}_i) \\
                & = \sum_{i=1}^L N_i^2 \frac{\sigma^2_i}{n_i} \frac{N_i-n_i}{N_i-1}
\end{align*}`

Dado que `$\sigma^2_i$` es usualmente desconocido, se emplea el estimador `$\hat{\sigma}^2_i = \frac{N_i-1}{N_i}S_i^2$`, dando como resultado el estimador insesgado para `$Var(\hat{\tau})$`, tal que
`\begin{align*}
Var(\hat{\tau}) & = \sum_{i=1}^L N_i^2 \frac{S^2_i}{n_i} \frac{N_i-n_i}{N_i}
\end{align*}`

#### Intervalos de confianza para el total de la población 
A partir del estimadores para el total de la población `$\hat{\tau}$` y la varianza del estimador `$Var(\hat{\tau})$`, es posible encontrar el límite de los errores de estimación `$B$`, en donde, para el caso en que `$n>30$`, el límite de los errores de estimación se define como
`\begin{align*}
B & = Z_{\alpha/2}\sqrt{Var(\hat{\tau})} \\ 
  & = Z_{\alpha/2}\sqrt{\sum_{i=1}^L N_i^2 \frac{S^2_i}{n_i}\frac{N_i-n_i}{N_i}}
\end{align*}`
en donde, el intervalos de confianza del `$(1-\alpha)100\%$` se definirá como
`\begin{align*}
\hat{\tau} \pm  Z_{\alpha/2}\sqrt{\sum_{i=1}^L N_i^2 \frac{S^2_i}{n_i}\frac{N_i-n_i}{N_i}}
\end{align*}`
Mientras que, para el caso de `$n\leq30$`, el límite de los errores de estimación se define como
`\begin{align*}
B & = Z_{\alpha/2}\sqrt{Var(\hat{\tau})} \\ 
  & = t_{\alpha/2,n-1}\sqrt{\sum_{i=1}^L N_i^2 \frac{S^2_i}{n_i}\frac{N_i-n_i}{N_i}}
\end{align*}`
junto a su intervalo de confianza del `$(1-\alpha)\times100\%$`
`\begin{align*}
\hat{\tau} \pm  t_{\alpha/2,n-1}\sqrt{\sum_{i=1}^L N_i^2 \frac{S^2_i}{n_i}\frac{N_i-n_i}{N_i}}
\end{align*}`

#### Estimación de la media poblacional `$\mu$`
Basados en la definición del parámetro `$\tau$`, es posible obtener una definición para la obtención del parámetro `$\mu$`, ya que `$\tau$` puede definirse como
`\begin{align*}
\tau = N\mu
\end{align*}`
y por tanto
\mu = \frac{\tau}{N}
Dado ésto, y el estimador del total de las poblaciones `$\hat{\tau}$`, podremos obtener un estimador para la media poblacional, tal que
`\begin{align*}
\hat{\mu} = \bar{Y}_t & = \frac{\hat{\tau}}{N} \\
                      & = \frac{1}{N}\sum_{i=1}^L N_i\bar{Y}_i
\end{align*}`

Entonces, como `$\bar{Y}_t$` depende de `$\hat{\tau}$` se puede calcular una expresión para la varianza de la media poblacional `$Var(\bar{Y})$`, tal que
`\begin{align*}
Var(\hat{\mu}) = Var(\bar{Y}_t) & = \frac{1}{N^2}Var(\hat{\tau}) \\
                                & = \sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{S^2}{n_i} \frac{N_i-n_i}{N_i}
\end{align*}`

#### Intervalos de confianza para la media poblacional
Una vez obtenida un estimador para la media poblacional y para la varianza de la media estimada, es posible presentar una expresión para el límites del error de estimación `$B$`. Si `$n>30$` el límite del error de estimación se define como
`\begin{align*}
B & = Z_{\alpha/2}\sqrt{Var(\bar{Y})} \\
  & = Z_{\alpha/2}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{S^2}{n_i} \frac{N_i-n_i}{N_i}}
\end{align*}`
junto a su intervalos de confianza del `$(1-\alpha)\times100\%$`
`\begin{align*}
\bar{Y} \pm  Z_{\alpha/2}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{S^2}{n_i} \frac{N_i-n_i}{N_i}}
\end{align*}`
y si `$n\leq 30$` el límite del error de estimación se define como
`\begin{align*}
B & = t_{\alpha/2, n-1}\sqrt{Var(\bar{Y})} \\ 
  & = t_{\alpha/2, n-1}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{S^2}{n_i} \frac{N_i-n_i}{N_i}}
\end{align*}`
y su intervalos de confianza del `$(1-\alpha)\times100\%$` será
`\begin{align*}
\bar{Y} \pm  t_{\alpha/2, n-1}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{S^2}{n_i} \frac{N_i-n_i}{N_i}}
\end{align*}`

#### Estimación de la proporción poblacional `$p$`
Para encontrar un estimador para la proporción poblacional `$p$`, considere a `$A$`: el total de individuos que cumplen con el atributo en la población y a `$A_i$`: el total de individuos que cumplen con el atributo en el i-ésimo estrato, para `$i=1,2, \ldots, L$`, entonces se tendrá que `$A$` puede expresarse como
`\begin{align*}
A = \sum_{i=1}^L A_i
\end{align*}`
El cual, al igual que los otros parámetros de la población no es generalmente conocido, y por tanto, un estimador insesgado para éste puede definirse como
`\begin{align*}
\hat{A} = \sum_{i=1}^L \hat{A_i} = \sum_{i=1}^L N_i\hat{p}_i
\end{align*}`
siendo `$\hat{p}_i$` la proporción estimada de los individuos en la muestra del i-ésimo estrato que cumple con el atributo de interés. En consecuencia, el estimador `$\hat{p}_i$` puede calcularse como
`\begin{align*}
\hat{p}_i = \frac{a_i}{n_i} = \frac{\text{Número de individuos que poseen el atributo en el i-ésimo estrato}}{\text{Número de unidades en la muestra pertenecientes al i-ésimo estrato}}
\end{align*}`

A partir de este estimador, y de forma similar al método de muestreo aleatorio simple, es posible definir la varianza para la proporción estimada `$Var(p)$`, tal que
`\begin{align*}
Var(\hat{A}) & = Var\left(\sum_{i=1}^L \hat{A_i} \right) = Var\left(\sum_{i=1}^L N_i\hat{p}_i \right) \\
             & = \sum_{i=1}^L Var\left(N_i\hat{p}_i \right) \\
             & = \sum_{i=1}^L N_i^2Var\left(\hat{p}_i \right) \\
             & = \sum_{i=1}^L N_i^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}
\end{align*}`

Ahora, basados en la definición del parámetro `$A$`, es posible obtener una definición para la obtención del parámetro `$p$`, ya que `$A$` puede definirse como
`\begin{align*}
A = Np
\end{align*}`
y por tanto `$p$` puede reescribirse como
p = \frac{A}{N}

Dado ésto, y que el estimador del total de individuos que cumplen con el atributo en la población `$\hat{A}$`, podremos obtener un estimador para la proporción poblacional, tal que
`\begin{align*}
\hat{p}_t & = \frac{\hat{A}}{N} \\
          & = \frac{1}{N}\sum_{i=1}^L N_i\hat{p}_i
\end{align*}`

Entonces, como `$\hat{p}_t$` depende de `$\hat{A}$` se puede calcular una expresión para la varianza de la proporción poblacional `$Var(\hat{p})$`, tal que
`\begin{align*}
Var(\hat{p}_t) & = \frac{1}{N^2}Var(\hat{A}) \\
               & = \sum_{i=1}^L\frac{N_i^2}{N^2} \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i} \\
               & = \sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}
\end{align*}`

#### Intervalos de confianza para la proporción poblacional
A partir de los valores anteriores, es posible calcular los intervalos de confianza para el caso de la proporción poblacional `$p$`, en donde, se tendrá que si `$n>30$`, el límite del error de estimación estará dado por
`\begin{align*}
B & = Z_{\alpha/2}\sqrt{Var(\hat{p})} \\ 
  & = Z_{\alpha/2}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}}
\end{align*}`

siendo el intervalo de confianza del `$100(1-\alpha)\%$` de confianza dado por
`\begin{align*}
\hat{p} \pm  Z_{\alpha/2}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}}
\end{align*}`

y si `$n\leq30$`, el límite del error de estimación se define como
`\begin{align*}
B & = t_{\alpha/2,n-1}\sqrt{Var(\hat{p})} \\ 
  & = t_{\alpha/2,n-1}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}}
\end{align*}`

junto a su correspondiente intervalo de confianza del `$100(1-\alpha)\%$` de confianza
`\begin{align*}
\hat{p} \pm  t_{\alpha/2,n-1}\sqrt{\sum_{i=1}^L\left(\frac{N_i}{N}\right)^2 \frac{p_i(1-p_i)}{n_i-1}\frac{N_i-n_i}{N_i}}
\end{align*}`